namespace Gwt.Agent.Services.SkillRegistration
{
    internal static class SkillAssets
    {
        internal static readonly ManagedAsset[] ProjectSkills = new[]
        {
            // 8 skills + sub-files - placeholders for now, will be generated by Editor script
            new ManagedAsset("skills/gwt-fix-pr/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-fix-pr/scripts/inspect_pr_checks.py", "placeholder", false, false),
            new ManagedAsset("skills/gwt-issue-ops/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-issue-ops/scripts/inspect_issue.py", "placeholder", false, false),
            new ManagedAsset("skills/gwt-pr/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-pr/references/pr-body-template.md", "placeholder", false, false),
            new ManagedAsset("skills/gwt-pr-check/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-project-index/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-pty-communication/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-spec-ops/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-spec-to-issue-migration/SKILL.md", "placeholder", false, true),
            new ManagedAsset("skills/gwt-spec-to-issue-migration/scripts/migrate-specs-to-issues.sh", "placeholder", true, false),
        };

        internal static readonly ManagedAsset[] ClaudeCommands = new[]
        {
            new ManagedAsset("commands/gwt-issue-ops.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-fix-pr.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-spec-ops.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-pr.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-pr-check.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-project-index.md", "placeholder", false, true),
            new ManagedAsset("commands/gwt-pty-communication.md", "placeholder", false, true),
        };

        internal static readonly ManagedAsset[] ClaudeHooks = new[]
        {
            new ManagedAsset("hooks/scripts/gwt-forward-hook.sh", "placeholder", true, false),
            new ManagedAsset("hooks/scripts/gwt-block-git-branch-ops.sh", "placeholder", true, false),
            new ManagedAsset("hooks/scripts/gwt-block-cd-command.sh", "placeholder", true, false),
            new ManagedAsset("hooks/scripts/gwt-block-file-ops.sh", "placeholder", true, false),
            new ManagedAsset("hooks/scripts/gwt-block-git-dir-override.sh", "placeholder", true, false),
        };
    }
}
