//! Worktree-local `CODEX_HOME` generator for SPEC-1921 FR-103 Backend
//! Override on Codex launches.
//!
//! Codex CLI does not honor pure env-var redirection for non-OpenAI
//! upstreams; instead it reads `[model_providers.<id>]` entries from
//! `~/.codex/config.toml`. To avoid mutating the user's global config, gwt
//! generates a worktree-local Codex config directory (mirroring the
//! OpenCode / Hermes pattern in SPEC-1921 FR-002 / FR-004) and points
//! `CODEX_HOME` at it for the duration of the launch.
//!
//! Reserved built-in provider ids (`openai`, `ollama`, `lmstudio`) are
//! avoided by prefixing gwt-managed providers with `gwt-` (e.g.
//! `gwt-llmlb`). Callers MUST honor [`codex_provider_id`] to compute the
//! safe id.

use std::path::{Path, PathBuf};

/// Default Codex wire API when the caller does not override
/// [`CodexHomeConfig::wire_api`].
pub const DEFAULT_WIRE_API: &str = "responses";

/// Reserved built-in Codex provider ids that gwt must not collide with.
pub const RESERVED_PROVIDER_IDS: &[&str] = &["openai", "ollama", "lmstudio"];

/// Configuration for a single Codex backend profile that gwt is about to
/// materialize. All fields are caller-derived so this module can live in
/// the skills crate without taking a transitive `gwt-agent` dependency.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CodexHomeConfig {
    /// Backend profile id (`[a-z0-9-]+`). Used to namespace generated
    /// provider names and env var keys.
    pub id: String,
    /// Human-readable display name shown in the generated `name = "..."`
    /// field.
    pub display_name: String,
    /// Upstream base URL (`http://` / `https://`).
    pub base_url: String,
    /// Default model id that Codex should use.
    pub model: String,
    /// Wire API protocol (`"chat"` or `"responses"`). Defaults to
    /// [`DEFAULT_WIRE_API`] when omitted.
    pub wire_api: Option<String>,
    /// Optional explicit env var name that carries the API key. When
    /// omitted, [`codex_env_key`] computes
    /// `GWT_CODEX_BACKEND_API_KEY_<UPPER>` from the profile id.
    pub env_key: Option<String>,
    /// Optional explicit `model_provider` id. When omitted,
    /// [`codex_provider_id`] computes `gwt-<id>` so the generated entry
    /// never collides with the reserved built-in providers.
    pub provider_id: Option<String>,
}

impl CodexHomeConfig {
    /// Effective `wire_api` for the generated provider entry.
    pub fn effective_wire_api(&self) -> &str {
        self.wire_api.as_deref().unwrap_or(DEFAULT_WIRE_API)
    }

    /// Effective `model_provider` id. Caller-overridden value is honored
    /// verbatim only when it does not collide with a reserved built-in id.
    /// Otherwise gwt falls back to the safe `gwt-<id>` namespace.
    pub fn effective_provider_id(&self) -> String {
        match &self.provider_id {
            Some(provided)
                if !RESERVED_PROVIDER_IDS
                    .iter()
                    .any(|r| r.eq_ignore_ascii_case(provided)) =>
            {
                provided.clone()
            }
            _ => codex_provider_id(&self.id),
        }
    }

    /// Effective `env_key` for the API key env var.
    pub fn effective_env_key(&self) -> String {
        self.env_key
            .clone()
            .unwrap_or_else(|| codex_env_key(&self.id))
    }
}

/// Default Codex `model_provider` id derived from a backend profile id.
pub fn codex_provider_id(profile_id: &str) -> String {
    format!("gwt-{profile_id}")
}

/// Default env var name that carries the API key for a Codex backend.
pub fn codex_env_key(profile_id: &str) -> String {
    let upper: String = profile_id
        .chars()
        .map(|c| {
            if c == '-' {
                '_'
            } else {
                c.to_ascii_uppercase()
            }
        })
        .collect();
    format!("GWT_CODEX_BACKEND_API_KEY_{upper}")
}

/// Render the generated `config.toml` content for the given backend
/// profile. Used both by [`materialize`] and by tests that want to assert
/// the rendered shape without touching the filesystem.
pub fn render_config_toml(config: &CodexHomeConfig) -> String {
    let provider_id = config.effective_provider_id();
    let env_key = config.effective_env_key();
    let wire_api = config.effective_wire_api();

    let mut out = String::new();
    out.push_str("# Generated by gwt — SPEC-1921 FR-103 Backend Override (do not edit by hand)\n");
    out.push_str(&format!(
        "model = \"{}\"\n",
        escape_toml_basic(&config.model)
    ));
    out.push_str(&format!(
        "model_provider = \"{}\"\n",
        escape_toml_basic(&provider_id)
    ));
    out.push('\n');
    out.push_str(&format!("[model_providers.{provider_id}]\n"));
    out.push_str(&format!(
        "name = \"{}\"\n",
        escape_toml_basic(&config.display_name)
    ));
    out.push_str(&format!(
        "base_url = \"{}\"\n",
        escape_toml_basic(&config.base_url)
    ));
    out.push_str(&format!("env_key = \"{}\"\n", escape_toml_basic(&env_key)));
    out.push_str(&format!("wire_api = \"{}\"\n", escape_toml_basic(wire_api)));
    out
}

/// Materialize a worktree-local `CODEX_HOME` at the given path. Creates
/// the directory and writes `config.toml` with [`render_config_toml`].
pub fn materialize(codex_home: &Path, config: &CodexHomeConfig) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(codex_home)?;
    let config_path = codex_home.join("config.toml");
    let rendered = render_config_toml(config);
    std::fs::write(&config_path, rendered)?;
    Ok(config_path)
}

/// Resolve the canonical worktree-local CODEX_HOME path under a worktree.
/// Mirrors the OpenCode / Hermes pattern (`.gwt/<provider>/`).
pub fn codex_home_for_worktree(worktree_root: &Path) -> PathBuf {
    worktree_root.join(".gwt").join("codex")
}

fn escape_toml_basic(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(id: &str) -> CodexHomeConfig {
        CodexHomeConfig {
            id: id.into(),
            display_name: "LM Studio".into(),
            base_url: "http://127.0.0.1:1234/v1".into(),
            model: "openai/gpt-oss-20b".into(),
            wire_api: None,
            env_key: None,
            provider_id: None,
        }
    }

    #[test]
    fn provider_id_uses_gwt_prefix_to_avoid_reserved_collisions() {
        assert_eq!(codex_provider_id("lmstudio"), "gwt-lmstudio");
        assert_eq!(codex_provider_id("llmlb"), "gwt-llmlb");
    }

    #[test]
    fn env_key_uppercases_and_replaces_dashes() {
        assert_eq!(
            codex_env_key("lmstudio"),
            "GWT_CODEX_BACKEND_API_KEY_LMSTUDIO"
        );
        assert_eq!(
            codex_env_key("multi-host-llm"),
            "GWT_CODEX_BACKEND_API_KEY_MULTI_HOST_LLM"
        );
    }

    #[test]
    fn effective_wire_api_defaults_to_responses() {
        let c = sample("llmlb");
        assert_eq!(c.effective_wire_api(), "responses");
    }

    #[test]
    fn effective_wire_api_honors_override() {
        let mut c = sample("llmlb");
        c.wire_api = Some("chat".into());
        assert_eq!(c.effective_wire_api(), "chat");
    }

    #[test]
    fn effective_provider_id_rejects_reserved_override() {
        // SPEC-1921 FR-103 safety: reserved built-in ids
        // (openai/ollama/lmstudio) MUST NOT be honored as provider_id
        // overrides, even if the user typed them — they would collide with
        // Codex's built-in providers.
        for reserved in RESERVED_PROVIDER_IDS {
            let mut c = sample("custom");
            c.provider_id = Some(reserved.to_string());
            assert_eq!(c.effective_provider_id(), "gwt-custom");
        }
    }

    #[test]
    fn effective_provider_id_honors_non_reserved_override() {
        let mut c = sample("custom");
        c.provider_id = Some("my-vault".into());
        assert_eq!(c.effective_provider_id(), "my-vault");
    }

    #[test]
    fn render_emits_expected_keys() {
        let rendered = render_config_toml(&sample("llmlb"));
        assert!(rendered.contains("model = \"openai/gpt-oss-20b\""));
        assert!(rendered.contains("model_provider = \"gwt-llmlb\""));
        assert!(rendered.contains("[model_providers.gwt-llmlb]"));
        assert!(rendered.contains("name = \"LM Studio\""));
        assert!(rendered.contains("base_url = \"http://127.0.0.1:1234/v1\""));
        assert!(rendered.contains("env_key = \"GWT_CODEX_BACKEND_API_KEY_LLMLB\""));
        assert!(rendered.contains("wire_api = \"responses\""));
    }

    #[test]
    fn render_escapes_special_characters_in_strings() {
        let mut c = sample("llmlb");
        c.display_name = "My \"Studio\" \\backslash".into();
        let rendered = render_config_toml(&c);
        assert!(rendered.contains("name = \"My \\\"Studio\\\" \\\\backslash\""));
    }

    #[test]
    fn materialize_creates_codex_home_directory_and_config() {
        let tmp = tempfile::tempdir().unwrap();
        let codex_home = tmp.path().join(".gwt").join("codex");
        let path = materialize(&codex_home, &sample("llmlb")).expect("materialize");

        assert!(codex_home.is_dir());
        assert_eq!(path, codex_home.join("config.toml"));
        let body = std::fs::read_to_string(&path).expect("read");
        assert!(body.contains("model_provider = \"gwt-llmlb\""));
    }

    #[test]
    fn materialize_overwrites_existing_config_idempotently() {
        let tmp = tempfile::tempdir().unwrap();
        let codex_home = tmp.path().join(".gwt").join("codex");
        std::fs::create_dir_all(&codex_home).unwrap();
        std::fs::write(codex_home.join("config.toml"), "stale = true\n").unwrap();

        materialize(&codex_home, &sample("llmlb")).expect("materialize");
        let body = std::fs::read_to_string(codex_home.join("config.toml")).expect("read");
        assert!(!body.contains("stale = true"));
        assert!(body.contains("[model_providers.gwt-llmlb]"));

        materialize(&codex_home, &sample("llmlb")).expect("materialize twice");
        let body2 = std::fs::read_to_string(codex_home.join("config.toml")).expect("read");
        assert_eq!(body, body2, "second materialize must be byte-identical");
    }

    #[test]
    fn codex_home_for_worktree_matches_managed_assets_pattern() {
        let wt = Path::new("/tmp/example-wt");
        assert_eq!(
            codex_home_for_worktree(wt),
            Path::new("/tmp/example-wt/.gwt/codex")
        );
    }
}
