//! Generated coordination guidance for gwt-managed worktrees.
//!
//! Writes a Claude Code / Codex auto-discovery skill (`gwt-coordination`)
//! into the target worktree so that Board posting and Work update
//! rules are applied by agents regardless of the target project's own
//! AGENTS.md / CLAUDE.md content.
//!
//! SPEC-1935 "Coordination Guidance Generator" closes the design gap
//! where `managed hooks` (existing) and `launch context` (existing) were
//! the only injection mechanisms; `generated guidance` is now backed by
//! this module.

use std::{io, path::Path};

use crate::settings_local::write_text_atomically;

/// Skill identifier (matches the `.claude/skills/<name>/` directory
/// segment that Claude Code's skill discovery looks for).
pub const SKILL_NAME: &str = "gwt-coordination";

/// Skill description surfaced in the auto-discovery listing. Designed to
/// trigger proactive invocation at the start of every conversation in a
/// gwt-managed worktree, independent of project documentation.
pub const SKILL_DESCRIPTION: &str = "Use proactively at the start of every conversation in any gwt-managed worktree, regardless of project AGENTS.md / CLAUDE.md content. Establishes Board posting (gwtd board post) and Work update (gwtd workspace update) rules for coordinating with other agents and the user. Mandatory when posting milestones, claiming scope, or updating current focus.";

const MANAGED_BEGIN: &str = "<!-- gwt-managed-begin: do not edit; regenerated by gwt -->";
const MANAGED_END: &str = "<!-- gwt-managed-end -->";

/// Canonical Board / Work operational guidance body (English).
///
/// This is the single source of truth referenced by both the generated
/// SKILL.md and (eventually) the runtime hook reminder. Drift between the
/// two is guarded by a phrase-presence test in `tests/`.
pub const SKILL_BODY_EN: &str = r#"# gwt Coordination

You are operating in a gwt-managed worktree. The Board (coordination
history) and Work (current state) MUST be used here. These rules
apply regardless of what the target project's AGENTS.md or CLAUDE.md
says (or does not say) about Board / Work; gwt's coordination
contract supersedes project-local documentation.

## Board (coordination history)

When you cross a reasoning milestone (phase change, alternative chosen,
or concern raised) or a coordination boundary (claim, next, handoff,
blocked, or decision), post to the shared Board.
Do not post tool-level updates such as "running gcc", "opening file X",
or "ran test Y". Do not repeat information already obvious from a diff
or command log.

Choose the audience before posting. If the post needs a reply, include
an explicit mention:

- `--mention user:<id>` - ask a human user for a response
- `--mention agent:<id>` - hand off to or question a specific agent type
- `--mention session:<id>` - reply to a running session
- `--mention branch:<name>` - target a workspace branch audience
- `--broadcast` - make the post visible repo-wide/cross-workspace

Without `--broadcast`, `gwtd board post` keeps the post scoped to the
current workspace and any audience implied by mentions. Do not assume
that omitting mentions creates a broadcast post.

Typical `--body` shape:

    Current state: <what changed or what was learned>
    Reason: <why it matters or why this decision was chosen>
    Next: <what happens next; omit when there is no next action>

Primary kinds:

- `--kind status` - phase change or hypothesis validation
- `--kind decision` - confirmed decision
- `--kind claim` - ownership claim to prevent collisions
- `--kind next` - next work broadcast
- `--kind blocked` - unblock request
- `--kind handoff` - concrete handoff

## Work (current state)

The Board is history; Work is current state. Update Work when
the current task, summary, next action, or focus changes:

    gwtd workspace update --agent-session "$GWT_SESSION_ID" \
      --current-focus '<current work>' \
      --title-summary '<short task title>'

`--title-summary` is the short task name used by Agent window tabs and
Work summaries. Write the work purpose, not its completion state, and
never copy the raw prompt into it. On a new Agent window, set it as your
first action, before responding to the user. If the purpose is not settled
yet, set a plausible provisional purpose now and update the same
`--title-summary` the moment the purpose is confirmed.

- Good: `Agent title summaries`
- Bad (completion state): `Agent title summaries done`, `Working on agent title summaries`
- Bad (activity / phase descriptors): `PR check in progress`, `verifying tests`, `fixing bug`, `checking CI`, `reviewing PR`

Rule: title-summary = work scope; phase / activity descriptors are for
`--current-focus` or Board `--body`. Keep the title stable while the
phase or activity changes, and update it only when the underlying work
scope changes (for example, starting a new task or moving to a
different Issue / SPEC).

Put completion, active, blocked, and similar state in `--status`,
`--current-focus`, `--summary`, or the Board `--body`, not in
`--title-summary`.

## Git environment

Do not manually create, switch, or delete branches/worktrees:

- Forbidden commands: `git checkout -b`, `git switch -c`,
  `git branch -D`, `git worktree add/remove`
- Git environment creation is owned by gwt Start Work / Launch
  materialization
- Existing branch switching, deletion, and renaming should happen only
  through human-driven operations

## Skills

`gwt-*` skill names (for example `gwt-search`, `gwt-discussion`) are
skills, never PATH executables. Do not resolve them with `command -v`
or `Get-Command`, and do not treat an empty PATH lookup as a missing
command. Invoke them through the runtime's skill mechanism, or follow
the executable commands written inside the skill's own SKILL.md.

## Persisted Work files

The tracked `.gwt/work/` directory is the persistent Work core
(SPEC-2359 W-15, FR-383). When you commit your work, include the
changed tracked files under `.gwt/work/` (`events.jsonl`, `memory.md`,
`discussions.md`) in the regular commit so they reach the base branch
through the PR:

- `.gwt/work/events.jsonl` is an append-only log joined across branches
  via the `merge=union` gitattribute. Never hand-edit, truncate, or
  revert it
- Do not commit it separately from the work it describes; ride the
  normal work commit

## Language

Write narrative Board bodies and Work summaries in Japanese.
Keep `gwtd` subcommands, flags, code examples, and technical identifiers
in English.

## Examples

    gwtd board post --kind claim --broadcast \
      --body $'現在の状態: migration slice を担当します。\n\nBoundary: 他 Agent は crates/gwt-core/src/migration.rs を避けてください。'

    gwtd board post --kind status --broadcast --title-summary '<short>' \
      --body $'現在の状態: focused tests が RED です。\n\n理由: CLI と hook output が multiline Board body を collapse しています。\n\n次: block rendering を実装します。'

    gwtd board post --kind handoff --mention agent:codex \
      --body $'現在の状態: phase 1 は local merge 済みです。\n\n次: Windows-focused verification を実行して failure を報告してください。'

    gwtd workspace update --agent-session "$GWT_SESSION_ID" \
      --current-focus 'SPEC-1935 Phase 2 writer' \
      --title-summary 'coordination guidance writer'
"#;

/// Localized Board / Work operational guidance body (Japanese).
///
/// This is kept as a translation aid only. `render_skill_md()` intentionally
/// emits `SKILL_BODY_EN` because skill definitions are authored in English.
pub const SKILL_BODY_JA: &str = r#"# gwt Coordination

You are operating in a gwt-managed worktree. The Board (coordination
history) and Work (current state) MUST be used here. These rules
apply regardless of what the target project's AGENTS.md or CLAUDE.md
says (or does not say) about Board / Work — gwt's coordination
contract supersedes project-local documentation.

## Board (coordination history)

推論の節目（phase change / alternative chosen / concern raised）または
協調境界（claim / next / handoff / blocked / decision）を越えたら共有
Board に投稿します。tool 単位の報告（"running gcc"、"opening file X"、
"ran test Y"）は post 禁止。diff や log で既に分かる内容も Board
entry にしません。

投稿前に audience を選びます。返答が必要な投稿は必ず mention 付きで:

- `--mention user:<id>` — 人間 user に返答を求める
- `--mention agent:<id>` — 特定 agent type に handoff / question
- `--mention session:<id>` — 実行中 session への返信
- `--mention branch:<name>` — workspace branch への broadcast
- mention 省略 → broadcast（返答不要のときだけ）

本文 (`--body`) の typical shape:

    現在の状態: <何が変わったか、何が分かったか>
    理由: <なぜ重要か、なぜその判断にしたか>
    次: <次に何をするか。なければ省略>

主要 kind:

- `--kind status` — 作業 phase の遷移 / 仮説検証
- `--kind decision` — 確定した判断
- `--kind claim` — 担当範囲を宣言して衝突回避
- `--kind next` — 次の作業を broadcast
- `--kind blocked` — unblock 要請
- `--kind handoff` — 具体的な引き継ぎ

## Work (current state)

Board が history なら Work は current state です。現在の task、
summary、next action、focus が変わったら必ず更新します:

    gwtd workspace update --agent-session "$GWT_SESSION_ID" \
      --current-focus '<現在の作業内容>' \
      --title-summary '<短い作業タイトル>'

`--title-summary` は Agent window tab と Work summary 用の
**短い作業名**。状態や結果ではなく「何の作業か（作業の目的）」を書きます。
入力した生プロンプトをそのまま使わないでください。新しい Agent window
では、応答を始める前に最初のアクションとして設定します。目的がまだ
固まっていない場合は、それっぽい暫定の目的を今すぐ設定し、目的が定まった
瞬間に同じ `--title-summary` を更新します。

- 例: `エージェントタイトル改善` ✓
- 不可 (完了状態): `エージェントタイトル改善完了`、`エージェントタイトル改善中` ✗
- 不可 (activity / phase): `PR チェック中`、`verifying tests`、`fixing bug`、`checking CI`、`reviewing PR` ✗

Rule: title-summary は作業の scope。phase / activity descriptor は
`--current-focus` または Board `--body` に書きます。title は phase /
activity が変わっても変えず、scope (新しい task や別 Issue / SPEC
への移行) が変わった時だけ更新します。

完了 / 進行中 / ブロック中などの状態は `--status`、`--current-focus`、
`--summary`、または Board `--body` に分けます。

## Git environment

branch / worktree の手動作成、切替、削除は禁止です:

- 禁止コマンド: `git checkout -b`、`git switch -c`、`git branch -D`、
  `git worktree add/remove`
- Git 環境の作成は **gwt Start Work / Launch materialization** が担当
- 既存 branch への切替・削除・名称変更も人間操作経由のみ

## Skills

`gwt-*` の skill 名（例: `gwt-search`、`gwt-discussion`）は skill であり、
PATH 上の実行ファイルではありません。`command -v` や `Get-Command` で
解決を試みず、PATH に見つからないことを「コマンド欠落」と扱わないで
ください。runtime の skill 機構で呼び出すか、skill 自身の SKILL.md に
書かれた実行コマンドに従います。

## Persisted Work files

追跡対象の `.gwt/work/` ディレクトリは Work の永続コアです
（SPEC-2359 W-15, FR-383）。作業を commit する際は、`.gwt/work/` 配下の
追跡ファイル（`events.jsonl`、`memory.md`、`discussions.md`）の変更を
通常の commit に含め、PR 経由で base branch に届けます:

- `.gwt/work/events.jsonl` は append-only ログで、`merge=union`
  gitattribute により branch を跨いで結合されます。手編集・切詰め・
  revert をしないでください
- 作業内容と切り離して単独 commit にせず、通常の作業 commit に乗せます

## Language

Board 投稿本文と Work summary は narrative outputs として
**日本語** で記述します。`gwtd` の subcommands、flags、code examples は
English のまま。

## Examples

    gwtd board post --kind claim --mention branch:feature/foo \
      --body $'現在の状態: migration slice を担当します。\n\nBoundary: 他 Agent は crates/gwt-core/src/migration.rs を避けてください。'

    gwtd board post --kind status --title-summary '<short>' \
      --body $'現在の状態: focused tests が RED です。\n\n理由: CLI と hook output が multiline Board body を collapse しています。\n\n次: block rendering を実装します。'

    gwtd board post --kind handoff --mention agent:codex \
      --body $'現在の状態: phase 1 は local merge 済みです。\n\n次: Windows-focused verification を実行して failure を報告してください。'

    gwtd workspace update --agent-session "$GWT_SESSION_ID" \
      --current-focus 'SPEC-1935 Phase 2 writer' \
      --title-summary 'coordination guidance writer'
"#;

/// Render the full SKILL.md content (frontmatter + managed markers +
/// body) for a target worktree. Idempotent and pure.
pub fn render_skill_md() -> String {
    format!(
        "---\nname: {name}\ndescription: {description}\n---\n\n{begin}\n\n{body}\n{end}\n",
        name = SKILL_NAME,
        description = SKILL_DESCRIPTION,
        begin = MANAGED_BEGIN,
        body = SKILL_BODY_EN,
        end = MANAGED_END,
    )
}

/// Materialize the gwt-coordination SKILL.md under both `.claude/skills/`
/// and `.codex/skills/` of the target worktree. Convenience wrapper used by
/// standalone callers and tests; the orchestrator prefers the
/// target-specific functions so it can honor per-agent target filters.
///
/// - Atomic write per file (durable rename, same pattern as
///   `generate_settings_local`).
/// - Idempotent: subsequent calls produce byte-identical files.
/// - User-edited content is overwritten by design — this is a gwt-managed
///   asset.
pub fn generate_coordination_guidance(worktree: &Path) -> io::Result<()> {
    generate_coordination_guidance_for_claude(worktree)?;
    generate_coordination_guidance_for_codex(worktree)?;
    Ok(())
}

/// Materialize the gwt-coordination SKILL.md under `.claude/skills/` only.
/// Used by the orchestrator when the target set includes `ClaudeCode` but
/// may exclude `Codex`.
pub fn generate_coordination_guidance_for_claude(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".claude").join("skills"))
}

/// Materialize the gwt-coordination SKILL.md under `.codex/skills/` only.
/// Used by the orchestrator when the target set includes `Codex` but may
/// exclude `ClaudeCode`.
pub fn generate_coordination_guidance_for_codex(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".codex").join("skills"))
}

fn write_skill_md(skills_root: &Path) -> io::Result<()> {
    let path = skills_root.join(SKILL_NAME).join("SKILL.md");
    write_text_atomically(&path, &render_skill_md())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn required_phrases() -> &'static [&'static str] {
        &[
            "Do not post tool-level updates",
            "--mention user:",
            "--mention agent:",
            "--mention session:",
            "--mention branch:",
            "--broadcast",
            "Without `--broadcast`",
            "gwtd workspace update",
            "--title-summary",
            "--kind status",
            "--kind decision",
            "--kind claim",
            "--kind next",
            "--kind blocked",
            "--kind handoff",
            "git checkout -b",
            "git worktree add/remove",
            ".gwt/work/",
            "events.jsonl",
            "merge=union",
            "AGENTS.md or CLAUDE.md",
            "skills, never PATH executables",
            "Get-Command",
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "title-summary = work scope",
        ]
    }

    #[test]
    fn render_skill_md_contains_required_canonical_phrases() {
        let rendered = render_skill_md();
        for phrase in required_phrases() {
            assert!(
                rendered.contains(phrase),
                "rendered SKILL.md is missing required canonical phrase: {phrase}\n\n--- rendered (first 4kB) ---\n{}",
                &rendered.chars().take(4096).collect::<String>()
            );
        }
    }

    #[test]
    fn render_skill_md_uses_english_canonical_body() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("When you cross a reasoning milestone"),
            "generated SKILL.md must use English canonical prose"
        );
        assert!(
            !rendered.contains("推論の節目"),
            "generated SKILL.md must not render the Japanese localized body as canonical prose"
        );
    }

    #[test]
    fn render_skill_md_documents_broadcast_flag_contract() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("--broadcast"),
            "generated SKILL.md must document the explicit repo-wide broadcast flag"
        );
        assert!(
            rendered.contains("Without `--broadcast`"),
            "generated SKILL.md must explain that omitted --broadcast keeps workspace/mention scoping"
        );
        assert!(
            !rendered.contains("mention 省略 → broadcast"),
            "generated SKILL.md must not claim that omitting mentions creates a broadcast post"
        );
    }

    #[test]
    fn render_skill_md_starts_with_yaml_frontmatter() {
        let rendered = render_skill_md();
        assert!(
            rendered.starts_with("---\n"),
            "SKILL.md must start with YAML frontmatter delimiter (---\\n)"
        );
        assert!(
            rendered.contains(&format!("name: {SKILL_NAME}\n")),
            "frontmatter must declare name: {SKILL_NAME}"
        );
        assert!(
            rendered.contains("description: Use proactively"),
            "frontmatter description must lead with the trigger keyword 'Use proactively'"
        );
        assert!(
            rendered.contains("regardless of project AGENTS.md / CLAUDE.md content"),
            "description must explicitly state project-AGENTS.md-independence"
        );
    }

    #[test]
    fn render_skill_md_wraps_body_in_managed_markers() {
        let rendered = render_skill_md();
        let begin_idx = rendered
            .find(MANAGED_BEGIN)
            .expect("managed begin marker missing");
        let end_idx = rendered
            .find(MANAGED_END)
            .expect("managed end marker missing");
        assert!(
            begin_idx < end_idx,
            "managed begin marker must precede managed end marker"
        );
    }

    #[test]
    fn generate_writes_skill_md_to_claude_and_codex_paths() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();

        let claude = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        let codex = tmp
            .path()
            .join(".codex/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");

        assert!(
            claude.exists(),
            "Claude SKILL.md not generated at {claude:?}"
        );
        assert!(codex.exists(), "Codex SKILL.md not generated at {codex:?}");

        let claude_content = std::fs::read_to_string(&claude).unwrap();
        let codex_content = std::fs::read_to_string(&codex).unwrap();
        assert_eq!(
            claude_content, codex_content,
            "Claude and Codex SKILL.md content must be byte-identical"
        );
        assert!(
            claude_content.contains("gwtd workspace update"),
            "written SKILL.md must contain canonical Workspace update directive"
        );
    }

    #[test]
    fn generate_for_claude_only_does_not_touch_codex_path() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance_for_claude(tmp.path()).unwrap();

        assert!(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Claude SKILL.md must be created"
        );
        assert!(
            !tmp.path()
                .join(".codex/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Codex SKILL.md must NOT be created when only Claude is requested"
        );
    }

    #[test]
    fn generate_for_codex_only_does_not_touch_claude_path() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance_for_codex(tmp.path()).unwrap();

        assert!(
            tmp.path()
                .join(".codex/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Codex SKILL.md must be created"
        );
        assert!(
            !tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Claude SKILL.md must NOT be created when only Codex is requested"
        );
    }

    #[test]
    fn generate_is_idempotent() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();
        let first = std::fs::read_to_string(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md"),
        )
        .unwrap();

        generate_coordination_guidance(tmp.path()).unwrap();
        let second = std::fs::read_to_string(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md"),
        )
        .unwrap();

        assert_eq!(
            first, second,
            "second invocation must produce byte-identical content (idempotent overwrite)"
        );
    }

    #[test]
    fn generate_overwrites_existing_stale_content() {
        let tmp = TempDir::new().unwrap();
        let path = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "stale content from prior version\n").unwrap();

        generate_coordination_guidance(tmp.path()).unwrap();
        let after = std::fs::read_to_string(&path).unwrap();

        assert!(
            !after.contains("stale content from prior version"),
            "stale content must be replaced — this is a gwt-managed file"
        );
        assert!(
            after.contains("gwtd workspace update"),
            "fresh content must contain canonical Workspace directive"
        );
    }

    #[test]
    fn skill_body_en_contains_activity_bad_examples_and_rule() {
        let body = SKILL_BODY_EN;
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "checking CI",
            "reviewing PR",
            "title-summary = work scope",
        ] {
            assert!(
                body.contains(phrase),
                "SKILL_BODY_EN must contain activity Bad example or rule phrase: {phrase}"
            );
        }
    }

    #[test]
    fn skill_body_ja_contains_activity_bad_examples_and_rule() {
        let body = SKILL_BODY_JA;
        for phrase in [
            "PR チェック中",
            "verifying tests",
            "fixing bug",
            "checking CI",
            "reviewing PR",
            "title-summary は作業の scope",
        ] {
            assert!(
                body.contains(phrase),
                "SKILL_BODY_JA must contain activity Bad example or rule phrase: {phrase}"
            );
        }
    }

    #[test]
    fn rendered_skill_md_propagates_activity_rule_to_emitted_file() {
        let rendered = render_skill_md();
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "title-summary = work scope",
        ] {
            assert!(
                rendered.contains(phrase),
                "render_skill_md() must propagate activity Bad example / rule: {phrase}"
            );
        }
    }

    #[test]
    fn generate_writes_byte_identical_skill_md_with_activity_rule_to_both_targets() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();

        let claude = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        let codex = tmp
            .path()
            .join(".codex/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");

        let claude_content = std::fs::read_to_string(&claude).unwrap();
        let codex_content = std::fs::read_to_string(&codex).unwrap();

        assert_eq!(
            claude_content, codex_content,
            "Claude and Codex SKILL.md must remain byte-identical for Phase U-9 parity"
        );
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "title-summary = work scope",
        ] {
            assert!(
                claude_content.contains(phrase),
                "materialized SKILL.md must carry the activity Bad example / rule: {phrase}"
            );
        }
    }

    #[test]
    fn skill_body_explicitly_overrides_project_agents_md() {
        // Compliance-gap regression guard: the SKILL.md body must
        // explicitly state that gwt's coordination rules supersede
        // project-local AGENTS.md / CLAUDE.md. Without this, agents
        // tend to deprioritize the skill in favor of empty project
        // context (see SPEC-1935 US-* design notes).
        let body = SKILL_BODY_EN;
        assert!(
            body.contains("AGENTS.md or CLAUDE.md"),
            "body must reference project AGENTS.md / CLAUDE.md to claim precedence"
        );
        assert!(
            body.contains("supersedes project-local documentation")
                || body.contains("regardless of"),
            "body must explicitly assert precedence over project docs"
        );
    }

    #[test]
    fn current_state_concept_uses_work_not_workspace() {
        // FR-357 (SPEC-2359 Phase W-12, Slice 1): the current-state concept
        // name must be "Work", not "Workspace". The `gwtd workspace update`
        // CLI subcommand name and the `workspace branch` mention-audience
        // wording are intentionally retained until the Slice 6 CLI rename;
        // only the current-state concept noun changes here.
        let rendered = render_skill_md();
        assert!(
            rendered.contains("## Work (current state)"),
            "current-state section heading must use the Work concept name"
        );
        assert!(
            !rendered.contains("## Workspace (current state)"),
            "current-state section heading must not use the Workspace concept name"
        );
        assert!(
            rendered.contains("Work is current state"),
            "guidance must state 'Work is current state'"
        );
        assert!(
            !rendered.contains("Workspace is current state"),
            "guidance must not use the legacy 'Workspace is current state' phrasing"
        );
        assert!(
            !SKILL_DESCRIPTION.contains("Workspace update"),
            "skill description must not use the Workspace concept name"
        );
        assert!(
            SKILL_DESCRIPTION.contains("Work update"),
            "skill description must use Work for the current-state concept"
        );
        // Japanese translation aid must follow the same concept rename.
        assert!(
            SKILL_BODY_JA.contains("## Work (current state)"),
            "JA current-state heading must use the Work concept name"
        );
        assert!(
            SKILL_BODY_JA.contains("Work は current state"),
            "JA guidance must state 'Work は current state'"
        );
        assert!(
            !SKILL_BODY_JA.contains("Workspace は current state"),
            "JA guidance must not use the legacy 'Workspace は current state' phrasing"
        );
        // The CLI subcommand example is retained until the Slice 6 rename.
        assert!(
            rendered.contains("gwtd workspace update"),
            "the gwtd workspace update CLI example is retained until the Slice 6 rename"
        );
    }
}
