//! Generated coordination guidance for gwt-managed worktrees.
//!
//! Writes a Claude Code / Codex auto-discovery skill (`gwt-coordination`)
//! into the target worktree so that Board posting and Work update
//! rules are applied by agents regardless of the target project's own
//! AGENTS.md / CLAUDE.md content.
//!
//! SPEC-1935 "Coordination Guidance Generator" closes the design gap
//! where `managed hooks` (existing) and `launch context` (existing) were
//! the only injection mechanisms; `generated guidance` is now backed by
//! this module.

use std::{io, path::Path};

use crate::settings_local::write_text_atomically;

/// Skill identifier (matches the `.claude/skills/<name>/` directory
/// segment that Claude Code's skill discovery looks for).
pub const SKILL_NAME: &str = "gwt-coordination";

/// Skill description surfaced in the auto-discovery listing. Designed to
/// trigger proactive invocation at the start of every conversation in a
/// gwt-managed worktree, independent of project documentation.
pub const SKILL_DESCRIPTION: &str = "Use proactively at the start of every conversation in any gwt-managed worktree, regardless of project AGENTS.md / CLAUDE.md content. Establishes Board posting and Work update rules through gwtd JSON envelopes for coordinating with other agents and the user. Mandatory when posting milestones, claiming scope, or updating current focus.";

const MANAGED_BEGIN: &str = "<!-- gwt-managed-begin: do not edit; regenerated by gwt -->";
const MANAGED_END: &str = "<!-- gwt-managed-end -->";

/// Canonical Board / Work operational guidance body (English).
///
/// This is the single source of truth referenced by both the generated
/// SKILL.md and (eventually) the runtime hook reminder. Drift between the
/// two is guarded by a phrase-presence test in `tests/`.
pub const SKILL_BODY_EN: &str = r#"# gwt Coordination

You are operating in a gwt-managed worktree. The Board (coordination
history) and Work (current state) MUST be used here. These rules
apply regardless of what the target project's AGENTS.md or CLAUDE.md
says (or does not say) about Board / Work; gwt's coordination
contract supersedes project-local documentation.

## Board (coordination history)

When you cross a reasoning milestone (phase change, alternative chosen,
or concern raised) or a coordination boundary (claim, next, handoff,
blocked, or decision), post to the shared Board.
Do not post tool-level updates such as "running gcc", "opening file X",
or "ran test Y". Do not repeat information already obvious from a diff
or command log.

Choose the audience before posting. If the post needs a reply, include
an explicit `params.mentions` entry:

- `user:<id>` - ask a human user for a response
- `agent:<id>` - hand off to or question a specific agent type
- `session:<id>` - reply to a running session
- `branch:<name>` - target a workspace branch audience
- `params.broadcast:true` - make the post visible repo-wide/cross-workspace

Without `params.broadcast:true`, `board.post` keeps the post scoped to
the current workspace and any audience implied by mentions. Do not
assume that omitting mentions creates a broadcast post.

Typical `params.body` shape:

    Current state: <what changed or what was learned>
    Reason: <why it matters or why this decision was chosen>
    Next: <what happens next; omit when there is no next action>

Primary kinds:

- `kind:"status"` - phase change or hypothesis validation
- `kind:"decision"` - confirmed decision
- `kind:"claim"` - ownership claim to prevent collisions
- `kind:"next"` - next work broadcast
- `kind:"blocked"` - unblock request
- `kind:"handoff"` - concrete handoff

### Blocked: escalating to the PM

The moment you conclude you cannot proceed in this window - a refused
operation, a decision only the owner can make, a missing tool, an
environment you cannot repair - post `kind:"blocked"` immediately. Do
not wait for the Stop gate. The routine
"ready for the next instruction" notice does not stand in for it: that
notice is a `status` post, it cannot say why you stopped, and while an
unblock request is open gwt withholds it entirely.

A blocked body MUST carry these four labelled lines, or `board.post`
refuses it:

    事象: <what happened; paste the refused operation and its exact error text>
    原因: <why you cannot proceed; say so plainly if the cause is unknown>
    依頼: <what you need from the PM: fresh launch / spec ruling / tool fix / ...>
    再開条件: <what has to be true before work can resume>

`Symptom:` / `Cause:` / `Request:` / `Resume:` are accepted in place of
the Japanese labels. Attach the owning Issue with `params.owners`; a
blocked post inherits your session's Issue when you omit it, and an
escalation with no owner cannot reach `issue.monitor.status`
`needs_human`.

Posting `blocked` also mirrors the same text onto the owning Issue as a
comment, because the Board scrolls and a closed pane takes its
transcript with it. If the mirror fails, the output tells you so - record
it yourself with `issue.comment`, so the next agent does not repeat your
investigation.

gwt files a `blocked` post on your behalf in two cases: when an
operation is refused on permission, immutability, or authority grounds
(for example `execution.reopen` on a completed record, or
`workspace.ensure` with a mismatched authority), and when you settle the
execution with `execution.blocked`, whose `params.reason` becomes the
escalation. Add the context gwt could not know; do not post a second
escalation for the same operation.

When the blocker clears, close the escalation explicitly - nothing else
does. Post with `params.resolves` naming the blocked entry id, which the
posting output and every PM-facing surface repeat back to you:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"decision","owners":["2338"],"resolves":["<blocked-entry-id>"],"body":"現在の状態: fresh launch を手配したので unblock 済みです。"}}
    JSON

### Waiting is not a stall: declare it

The Issue Monitor judges a launched agent stuck when it sees no activity
for `stuck_timeout_secs` (30 minutes by default), and each stuck verdict
costs an autonomous attempt. Waiting on a host-exclusivity turn, on a PM
serialization ruling, or on a long verification run you must not touch
produces no activity either, so before you go quiet for that long,
declare the wait:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"issue.monitor.wait","params":{"reason":"host 排他の順番待ち","resume_condition":"Issue 3791 の verify.run が完了する"}}
    JSON

`number` defaults to the owner Issue of this launch. While the
declaration is in force stuck detection skips your issue and the PM reads
`reason` / `resume_condition` / `expires_at` from the `waiting` field of
your row in `issue.monitor.status`. It is capped (`max_wait_secs` in the
response, 3 hours): re-declaring refreshes the text but never the cap, and
past it the ordinary rule applies again. Clear it the moment you resume:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"issue.monitor.wait","params":{"clear":true}}
    JSON

Do not fake activity instead (periodic `workspace.update` or Board posts
to look alive) - a declared wait is the honest signal.

### Proposing new Issues to the PM

Do not call `issue.create`. When you find something that deserves its own
Issue, post `kind:"decision"` mentioning the PM and let the PM register it,
so duplicates are caught before two Issues exist rather than after. The
proposal body MUST carry four items: 事象 (with primary evidence), 既存
Issue で扱えない根拠 (including your duplicate-search result), 提案 AC,
and 緊急度 (whether it blocks another PR or agent). The PM replies on the
Board with the registered Issue number, threaded under your proposal via
`params.parent`, so watch for a reply carrying your proposal's entry id.

Commenting on an existing Issue with `issue.comment` is never restricted
- add evidence, propose acceptance criteria, and share analysis freely.
Only creating a new Issue routes through the PM.

### Friction in gwt itself takes the same route

Friction and capability gaps in gwt itself - a hook, launch, skill, index,
verification, coordination, or Issue/SPEC workflow that contradicts what gwt
told you to do - is reported the same way: post it to the Board for the PM,
who registers it with `gwt-register-issue`. Never file an Issue upstream in
the gwt repository yourself, and never work around it silently. Include the
contract you were following, what you observed instead, and the primary
evidence (command, output, file and line). gwt has no automatic capture for
this; the Board post is the intake.

## Work (current state)

The Board is history; Work is current state. Update Work with a JSON
envelope when the current task, summary, next action, or focus changes:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"workspace.update","params":{"purpose":"<short task title>","current_focus":"<current work>"}}
    JSON

`purpose` is the short task name used by Agent window tabs and Work
summaries. Write the work purpose, not its completion state, and never
copy the raw prompt into it. On a new Agent window, set it as your first
action, before responding to the user. If the purpose is not settled yet,
set a plausible provisional purpose now and update the same purpose the
moment it is confirmed.

- Good: `Agent title summaries`
- Bad (completion state): `Agent title summaries done`, `Working on agent title summaries`
- Bad (activity / phase descriptors): `PR check in progress`, `verifying tests`, `fixing bug`, `checking CI`, `reviewing PR`

Rule: purpose = work scope; phase / activity descriptors are for
`current_focus` or Board `body`. Keep the title stable while the
phase or activity changes, and update it only when the underlying work
scope changes (for example, starting a new task or moving to a
different Issue / SPEC).

Put completion, active, blocked, and similar state in `params.status`,
`current_focus`, `summary`, or the Board `body`, not in `purpose`.

The Work detail renders purpose and status as separate layers — the
purpose leads, with the current focus
(`current_focus`) and next below it, and the Board body lands only as a
demoted latest-update snapshot. So update
purpose and status as distinct fields;
do not fold a status snapshot into the purpose, and do not rely on the
Board body to convey what the Work is.

### Terminal Work delivery

Make the final Work update before terminal operations, then converge in this
exact order: `final Work update -> commit/push -> fresh verification -> PR mutation -> execution/build completion`. After the final Work update or a
terminal lifecycle transition, do not issue another `workspace.update`; keep
blocker/recovery coordination on the Board or in a Draft PR comment instead.
Set `params.status:"done"` on that explicit final update; its successful event
append opens the machine-local delivery obligation used by Stop and final gates.

Include new immutable event shards under
`.gwt/work/events/<digest-prefix>/*.jsonl` in the
related source commit. Writer temp files matching
`.gwt/work/events/<digest-prefix>/.*.jsonl.create-*` remain untracked and must never be
committed. If no source change remains and the event shard is the only
bookkeeping change, use a scoped Conventional Commit whose subject starts with
the exact `chore(work):` prefix. gwt never commits or pushes this event
automatically. Completion and PR
mutations remain blocked until the current HEAD is confirmed on the configured
upstream, and verification must be run fresh after that commit/push.

## Git environment

Do not manually create, switch, or delete branches/worktrees:

- Forbidden commands: `git checkout -b`, `git switch -c`,
  `git branch -D`, `git worktree add/remove`
- Git environment creation is owned by gwt Start Work / Launch
  materialization
- Existing branch switching, deletion, and renaming should happen only
  through human-driven operations

## Skills

`gwt-*` skill names (for example `gwt-search`, `gwt-discussion`) are
skills, never PATH executables. Do not resolve them with `command -v`
or `Get-Command`, and do not treat an empty PATH lookup as a missing
command. Invoke them through the runtime's skill mechanism, or follow
the executable commands written inside the skill's own SKILL.md.
Semantic search runs through the `search` JSON operation of the resolved
gwtd binary:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"search","params":{"query":"query","scopes":["issues"],"n_results":8}}
    JSON

There is no standalone `gwt-search` executable.

## Heavy commands

`cargo test`, `cargo clippy`, `cargo build`, coverage, and headed browser
runs compile on a host shared with every other agent worktree. Take the
host-wide lease before any of them, even a single focused test, and
release it afterwards:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"verify.lease.acquire","params":{"ttl_minutes":45,"reason":"Issue 3913 RED run"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"verify.lease.release","params":{"lease_id":"<lease_id>"}}
    JSON

A refused acquire names the current holder; declare the wait with
`issue.monitor.wait` (see "Waiting is not a stall") and retry on the
cadence the gwt-verify skill defines instead of running without it.
`verify.run` admits itself: it honors a lease this worktree holds,
otherwise claims one and waits for other worktrees' heavy processes to
drain, and answers `deferred` when its bounded wait runs out — rerun it.

## Persisted Work files

The tracked `.gwt/work/` directory is the persistent Work core
(SPEC-2359 W-33). When you commit your work, include the new tracked
immutable event shard under `.gwt/work/events/<digest-prefix>/*.jsonl` in the
regular commit so they reach the base branch through the PR:

- Each `.gwt/work/events/<digest-prefix>/*.jsonl` file is an immutable event shard. Never hand-edit, append to, delete, truncate, overwrite, or revert a shard
- `.gwt/work/events/<digest-prefix>/.*.jsonl.create-*` is untracked writer temp residue,
  not Work history and not a delivery target
- Existing flat `.gwt/work/events/*.jsonl` shards are frozen read-only
  compatibility history and are never a new-write target
- `.gwt/work/events.jsonl` is frozen read-only compatibility history. Its
  existing `merge=union` behavior is retained only for legacy lines. Never hand-edit, append to, delete, truncate, overwrite, or revert this file
- If the target repository broadly ignores `.gwt/`, stage every exact new
  shard individually. Discover ignored candidates with
  `git ls-files --others --ignored --exclude-standard -- .gwt/work/events`,
  select only canonical `<2hex>/<64hex>.jsonl` paths, and repeat
  `git add -f -- .gwt/work/events/<digest-prefix>/<digest>.jsonl`. Never
  force-add the event directory or another managed subtree
- Do not commit a shard separately from the work it describes; ride the
  normal work commit

Project memory and discussion notes are machine-local scratch
(SPEC-3214 FR-007/FR-008). `memory.add` and the discussion operations
write `~/.gwt/projects/<repo-hash>/work-notes/{memory.md,discussions.md}`,
shared by every worktree of the repository. Do not commit them — a
legacy repo-local `.gwt/work/{memory.md,discussions.md}` is only a read
fallback that is imported into the home file once. Durable team-shared
learnings and decisions belong to GitHub (Issue / `gwt-spec` Issue),
not to the local notes.

## Language

Write narrative Board bodies and Work summaries in Japanese.
Keep `gwtd` operation names, JSON field names, code examples, and
technical identifiers in English.

## Examples

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"claim","broadcast":true,"body":"現在の状態: migration slice を担当します。\n\nBoundary: 他 Agent は crates/gwt-core/src/migration.rs を避けてください。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"status","broadcast":true,"body":"現在の状態: focused tests が RED です。\n\n理由: CLI と hook output が multiline Board body を collapse しています。\n\n次: block rendering を実装します。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"handoff","mentions":["agent:codex"],"body":"現在の状態: phase 1 は local merge 済みです。\n\n次: Windows-focused verification を実行して failure を報告してください。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"workspace.update","params":{"purpose":"coordination guidance writer","current_focus":"SPEC-1935 Phase 2 writer"}}
    JSON
"#;

/// Localized Board / Work operational guidance body (Japanese).
///
/// This is kept as a translation aid only. The rendered skill body is derived
/// from `SKILL_BODY_EN` because skill definitions are authored in English.
pub const SKILL_BODY_JA: &str = r#"# gwt Coordination

You are operating in a gwt-managed worktree. The Board (coordination
history) and Work (current state) MUST be used here. These rules
apply regardless of what the target project's AGENTS.md or CLAUDE.md
says (or does not say) about Board / Work — gwt's coordination
contract supersedes project-local documentation.

## Board (coordination history)

推論の節目（phase change / alternative chosen / concern raised）または
協調境界（claim / next / handoff / blocked / decision）を越えたら共有
Board に投稿します。tool 単位の報告（"running gcc"、"opening file X"、
"ran test Y"）は post 禁止。diff や log で既に分かる内容も Board
entry にしません。

投稿前に audience を選びます。返答が必要な投稿は必ず `params.mentions`
付きで:

- `user:<id>` — 人間 user に返答を求める
- `agent:<id>` — 特定 agent type に handoff / question
- `session:<id>` — 実行中 session への返信
- `branch:<name>` — workspace branch への audience
- `params.broadcast:true` — repo-wide / cross-workspace に表示

`params.broadcast:true` がない `board.post` は current workspace と
mentions 由来の audience に scope されます。mention 省略を broadcast
として扱わないでください。

本文 (`params.body`) の typical shape:

    現在の状態: <何が変わったか、何が分かったか>
    理由: <なぜ重要か、なぜその判断にしたか>
    次: <次に何をするか。なければ省略>

主要 kind:

- `kind:"status"` — 作業 phase の遷移 / 仮説検証
- `kind:"decision"` — 確定した判断
- `kind:"claim"` — 担当範囲を宣言して衝突回避
- `kind:"next"` — 次の作業を broadcast
- `kind:"blocked"` — unblock 要請
- `kind:"handoff"` — 具体的な引き継ぎ

### Blocked: PM へのエスカレーション

この window では進められないと結論した瞬間（operation の拒否、owner に
しかできない判断、欠けているツール、自力で直せない環境）に
`kind:"blocked"` を投稿します。Stop gate を待たないでください。定型の
"ready for the next instruction" は `status` 投稿であり停止理由を表現
できないため代用になりません。未解決の unblock 要請がある間、gwt はその
定型投稿自体を抑止します。

blocked の本文には次の 4 項目を必ずラベル行として含めます。欠けている
場合 `board.post` は投稿を拒否します:

    事象: <何が起きたか。拒否された operation とエラー文言をそのまま貼る>
    原因: <なぜ進めないのか。未判明ならそう書く>
    依頼: <PM に何をしてほしいか: fresh launch / 仕様裁定 / ツール修正 など>
    再開条件: <何が満たされれば作業を再開できるか>

`Symptom:` / `Cause:` / `Request:` / `Resume:` も受け付けます。担当 Issue
は `params.owners` で付けます（省略時は session の Issue を継承）。owner の
無い escalation は `issue.monitor.status` の `needs_human` に届きません。

blocked 投稿は同じ本文を担当 Issue のコメントにも自動でミラーします。
Board は流れ、pane は閉じれば transcript ごと消えるためです。ミラーに
失敗した場合は出力にその旨が出るので、`issue.comment` で自分で記録し、
次の担当が同じ調査をやり直さないようにします。

次の 2 つのケースでは gwt が代わりに `blocked` を起票します: permission /
immutability / authority 由来で operation が拒否された場合（例: 完了済み
record への `execution.reopen`、authority 不整合の `workspace.ensure`）と、
`execution.blocked` で execution を終端させた場合（`params.reason` が
escalation 本文になります）。gwt が知り得ない文脈を補足し、同じ operation
について二重に起票しないでください。

blocker が解消したら、必ず明示的に escalation を閉じます（他の投稿では
閉じません）。投稿出力と PM 向けの各面が entry id を提示するので、
`params.resolves` にその id を指定して投稿します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"decision","owners":["2338"],"resolves":["<blocked-entry-id>"],"body":"現在の状態: fresh launch を手配したので unblock 済みです。"}}
    JSON

### 待機は停滞ではない: 申告する

Issue Monitor は `stuck_timeout_secs`（既定 30 分）活動が無い launched agent
を stuck と判定し、判定ごとに autonomous attempt を 1 つ消費します。host
排他の順番待ち、PM の直列化裁定待ち、触ってはいけない長時間 verification
の完走待ちも活動を生まないため、その長さの沈黙に入る前に待機を申告します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"issue.monitor.wait","params":{"reason":"host 排他の順番待ち","resume_condition":"Issue 3791 の verify.run が完了する"}}
    JSON

`number` は省略するとこの launch の担当 Issue になります。申告が有効な間は
stuck 判定が自分の Issue をスキップし、PM は `issue.monitor.status` の自分の
行の `waiting` フィールドから `reason` / `resume_condition` / `expires_at` を
読めます。申告には上限があります（応答の `max_wait_secs`、3 時間）。再申告は
本文を更新しますが上限は延びず、超過後は通常の判定に戻ります。再開したら
すぐ解除します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"issue.monitor.wait","params":{"clear":true}}
    JSON

生存を装うために定期的な `workspace.update` や Board 投稿で活動を偽装しない
でください。待機の申告が正直なシグナルです。

### Issue 化は PM へ提案する

`issue.create` を直接呼ばないでください。Issue 化すべき事象を見つけたら
PM を mention した `kind:"decision"` を投稿し、登録は PM が行います。
登録主体を 1 つにすることで、重複を「登録後」ではなく「登録前」に検出
できます。提案本文には 4 項目を必ず含めます: 事象（一次証拠つき）、既存
Issue で扱えない根拠（重複検索の結果を含む）、提案 AC、緊急度（他の PR /
agent をブロックしているか）。PM は登録した Issue 番号を返すので、Board
の返信を確認してください。

既存 Issue への `issue.comment` は一切制限しません。証拠の追記、AC の提案、
分析の共有は自由に行ってください。制限するのは新規 Issue の登録だけです。
PM は登録した Issue 番号を、提案投稿の entry id を `params.parent` に
指定した Board 返信で返します。

### gwt 自体の摩擦・機能ギャップも同じ経路

gwt 自体の摩擦や機能ギャップ（hook、launch、skill、index、verification、
coordination、Issue/SPEC workflow が gwt の指示と食い違う）も同じ経路で
扱います。Board に投稿して PM へ報告し、PM が `gwt-register-issue` で
起票します。gwt リポジトリに自分で Issue を作らないでください。黙って
回避するのも禁止です。投稿には、従っていた契約、実際に観測した挙動、
一次証拠（コマンド、出力、ファイルと行）を含めます。自動捕捉の仕組みは
無く、この Board 投稿が唯一の intake です。

## Work (current state)

Board が history なら Work は current state です。現在の task、
summary、next action、focus が変わったら JSON envelope で必ず更新します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"workspace.update","params":{"purpose":"<短い作業タイトル>","current_focus":"<現在の作業内容>"}}
    JSON

`purpose` は Agent window tab と Work summary 用の
**短い作業名**です。状態や結果ではなく「何の作業か（作業の目的）」を書きます。
入力した生プロンプトをそのまま使わないでください。新しい Agent window
では、応答を始める前に最初のアクションとして設定します。目的がまだ
固まっていない場合は、それっぽい暫定の目的を今すぐ設定し、目的が定まった
瞬間に同じ purpose を更新します。

- 例: `エージェントタイトル改善` ✓
- 不可 (完了状態): `エージェントタイトル改善完了`、`エージェントタイトル改善中` ✗
- 不可 (activity / phase): `PR チェック中`、`verifying tests`、`fixing bug`、`checking CI`、`reviewing PR` ✗

Rule: purpose は作業の scope。phase / activity descriptor は
`current_focus` または Board `body` に書きます。title は phase /
activity が変わっても変えず、scope (新しい task や別 Issue / SPEC
への移行) が変わった時だけ更新します。

完了 / 進行中 / ブロック中などの状態は `params.status`、`current_focus`、
`summary`、または Board `body` に分けます。

Work detail は purpose と status を別レイヤーで表示します — purpose
を見出しに、その下に現在地（`current_focus`）と
次、Board body は降格した latest-update スナップショットとして表示
されます。purpose と status は別フィールドとして更新し、状態スナップ
ショットを purpose に混ぜたり、Work が何かを Board body で伝えようと
したりしないでください。

### Terminal Work delivery

terminal operation の前に final Work update を行い、以後は exact
`final Work update -> commit/push -> fresh verification -> PR mutation -> execution/build completion`
の順で収束します。final Work update または terminal lifecycle transition
の後は、別の `workspace.update` を実行しません。blocker / recovery coordination
は Board または Draft PR comment に残します。
explicit final update では `params.status:"done"` を設定します。event append
が成功すると、Stop と final gate が使用する machine-local delivery obligation
が開きます。

新しい immutable event shard `.gwt/work/events/<digest-prefix>/*.jsonl` は関連 source commit に
含めます。`.gwt/work/events/<digest-prefix>/.*.jsonl.create-*` に一致する writer temp は未追跡の
ままとし、commit してはいけません。source change が残らず event shard だけが
bookkeeping change の場合は、subject が exact `chore(work):` prefix で始まる
scoped Conventional Commit を使用します。gwt は event を自動 commit / push
しません。current HEAD が configured upstream に存在することを
確認するまで completion / PR mutation は block され、その commit / push 後に
fresh verification を実行します。

## Git environment

branch / worktree の手動作成、切替、削除は禁止です:

- 禁止コマンド: `git checkout -b`、`git switch -c`、`git branch -D`、
  `git worktree add/remove`
- Git 環境の作成は **gwt Start Work / Launch materialization** が担当
- 既存 branch への切替・削除・名称変更も人間操作経由のみ

## Skills

`gwt-*` の skill 名（例: `gwt-search`、`gwt-discussion`）は skill であり、
PATH 上の実行ファイルではありません。`command -v` や `Get-Command` で
解決を試みず、PATH に見つからないことを「コマンド欠落」と扱わないで
ください。runtime の skill 機構で呼び出すか、skill 自身の SKILL.md に
書かれた実行コマンドに従います。セマンティック検索は解決済み gwtd
binary の `search` JSON operation で実行します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"search","params":{"query":"query","scopes":["issues"],"n_results":8}}
    JSON

`gwt-search` という単体の実行ファイルは存在しません。

## Heavy commands

`cargo test`、`cargo clippy`、`cargo build`、coverage、headed browser 実行は、
他のすべての agent worktree と共有する host 上でコンパイルします。単発の
focused test でも、開始前に host 全体の lease を取り、終わったら解放します:

    gwtd <<'JSON'
    {"schema_version":1,"operation":"verify.lease.acquire","params":{"ttl_minutes":45,"reason":"Issue 3913 RED run"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"verify.lease.release","params":{"lease_id":"<lease_id>"}}
    JSON

拒否された acquire は現在の保持者を返します。lease 無しで実行せず、
`issue.monitor.wait` で待機を申告して（「待機は停滞ではない」参照）、
gwt-verify skill が定める間隔で再試行してください。`verify.run` は
自分で admission を取ります: この worktree が保持する lease はそのまま使い、
無ければ取得して他 worktree の heavy プロセスが捌けるまで待ち、bounded な
待機を使い切ると `deferred` を返します。その場合は再実行してください。

## Persisted Work files

追跡対象の `.gwt/work/` ディレクトリは Work の永続コアです
（SPEC-2359 W-33）。作業を commit する際は、新しい追跡対象の
immutable event shard `.gwt/work/events/<digest-prefix>/*.jsonl` を通常の commit に含め、PR 経由で
base branch に届けます:

- `.gwt/work/events/<digest-prefix>/*.jsonl` の各ファイルは immutable event shard です。
  shard の手編集・追記・削除・切詰め・上書き・revert を禁止します
- `.gwt/work/events/<digest-prefix>/.*.jsonl.create-*` は未追跡の writer temp residue であり、
  Work history でも delivery 対象でもありません
- 既存の flat `.gwt/work/events/*.jsonl` shard は frozen な read-only
  compatibility history であり、新規書込先にはしません
- `.gwt/work/events.jsonl` は frozen な read-only compatibility history です。
  既存の `merge=union` は legacy 行の互換性のためだけに維持します。この
  ファイルの手編集・追記・削除・切詰め・上書き・revert を禁止します
- target repository が `.gwt/` を広く ignore している場合は、すべての exact な新規
  shard を1つずつ stage します。`git ls-files --others --ignored --exclude-standard -- .gwt/work/events`
  で候補を列挙し、canonical な `<2hex>/<64hex>.jsonl` path だけを選び、
  `git add -f -- .gwt/work/events/<digest-prefix>/<digest>.jsonl` を各 path で繰り返します。
  events directory や他の managed subtree 全体を force-add してはいけません
- shard は作業内容と切り離して単独 commit にせず、通常の作業 commit に乗せます

プロジェクト memory と discussion notes はマシンローカルの scratch です
（SPEC-3214 FR-007/FR-008）。`memory.add` と discussion 系 operation は
`~/.gwt/projects/<repo-hash>/work-notes/{memory.md,discussions.md}` に
書き込み、同一 repository の全 worktree で共有されます。これらを commit
しないでください — legacy な repo-local `.gwt/work/{memory.md,discussions.md}`
は読み取り fallback のみで、初回書き込み時に home 側へ import されます。
チーム共有すべき durable な学び・決定は GitHub（Issue / `gwt-spec` Issue）
に反映します。

## Language

Board 投稿本文と Work summary は narrative outputs として
**日本語** で記述します。`gwtd` operation 名、JSON field 名、code examples は
English のまま。

## Examples

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"claim","mentions":["branch:feature/foo"],"body":"現在の状態: migration slice を担当します。\n\nBoundary: 他 Agent は crates/gwt-core/src/migration.rs を避けてください。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"status","body":"現在の状態: focused tests が RED です。\n\n理由: CLI と hook output が multiline Board body を collapse しています。\n\n次: block rendering を実装します。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"board.post","params":{"kind":"handoff","mentions":["agent:codex"],"body":"現在の状態: phase 1 は local merge 済みです。\n\n次: Windows-focused verification を実行して failure を報告してください。"}}
    JSON

    gwtd <<'JSON'
    {"schema_version":1,"operation":"workspace.update","params":{"purpose":"coordination guidance writer","current_focus":"SPEC-1935 Phase 2 writer"}}
    JSON
"#;

/// Render the full SKILL.md content (frontmatter + managed markers + body).
/// Idempotent and pure. Since SPEC #3245 the guidance is a single body for
/// every session (FR-004) and the lane mechanism itself is gone (FR-007).
pub fn render_skill_md() -> String {
    format!(
        "---\nname: {name}\ndescription: {description}\n---\n\n{begin}\n\n{body}\n{end}\n",
        name = SKILL_NAME,
        description = SKILL_DESCRIPTION,
        begin = MANAGED_BEGIN,
        body = SKILL_BODY_EN,
        end = MANAGED_END,
    )
}

/// Materialize the gwt-coordination SKILL.md under both `.claude/skills/`
/// and `.codex/skills/` of the target worktree. Convenience wrapper used by
/// standalone callers and tests; the orchestrator prefers the
/// target-specific functions so it can honor per-agent target filters.
///
/// - Atomic write per file (durable rename, same pattern as
///   `generate_settings_local`).
/// - Idempotent: subsequent calls produce byte-identical files.
/// - User-edited content is overwritten by design — this is a gwt-managed
///   asset.
pub fn generate_coordination_guidance(worktree: &Path) -> io::Result<()> {
    generate_coordination_guidance_for_claude(worktree)?;
    generate_coordination_guidance_for_codex(worktree)?;
    Ok(())
}

/// Materialize the gwt-coordination SKILL.md under `.claude/skills/` only.
/// Used by the orchestrator when the target set includes `ClaudeCode` but
/// may exclude `Codex`.
pub fn generate_coordination_guidance_for_claude(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".claude").join("skills"))
}

/// Materialize the gwt-coordination SKILL.md under `.codex/skills/` only.
/// Used by the orchestrator when the target set includes `Codex` but may
/// exclude `ClaudeCode`.
pub fn generate_coordination_guidance_for_codex(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".codex").join("skills"))
}

fn write_skill_md(skills_root: &Path) -> io::Result<()> {
    let path = skills_root.join(SKILL_NAME).join("SKILL.md");
    write_text_atomically(&path, &render_skill_md())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn required_phrases() -> &'static [&'static str] {
        &[
            "Do not post tool-level updates",
            "`user:<id>`",
            "`agent:<id>`",
            "`session:<id>`",
            "`branch:<name>`",
            "params.broadcast:true",
            "Without `params.broadcast:true`",
            "gwtd <<'JSON'",
            "\"operation\":\"workspace.update\"",
            "\"purpose\"",
            "kind:\"status\"",
            "kind:\"decision\"",
            "kind:\"claim\"",
            "kind:\"next\"",
            "kind:\"blocked\"",
            "kind:\"handoff\"",
            "git checkout -b",
            "git worktree add/remove",
            ".gwt/work/",
            "events.jsonl",
            "merge=union",
            "AGENTS.md or CLAUDE.md",
            "skills, never PATH executables",
            "Get-Command",
            "\"operation\":\"search\"",
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "purpose = work scope",
            "purpose and status as distinct fields",
            "final Work update -> commit/push -> fresh verification -> PR",
            "do not issue another `workspace.update`",
            "`params.status:\"done\"`",
            "exact `chore(work):` prefix",
            "gwt never commits or pushes",
            // Issue #3655 AC-7: the escalation contract is only as reliable as
            // its presence in the guidance every gwt-managed session loads.
            "事象:",
            "原因:",
            "依頼:",
            "再開条件:",
            "params.resolves",
            "issue.monitor.status",
            "needs_human",
            "Do not call `issue.create`",
        ]
    }

    /// Issue #3655 AC-7 / AC-10 / AC-12: both bodies and the generated file
    /// must carry the escalation and Issue-proposal contracts, or an agent
    /// reading only the skill has no way to know either rule exists.
    #[test]
    fn escalation_and_issue_proposal_contracts_are_in_both_bodies_and_the_generated_file() {
        for phrase in [
            "事象:",
            "原因:",
            "依頼:",
            "再開条件:",
            "params.resolves",
            "needs_human",
            "issue.comment",
        ] {
            assert!(SKILL_BODY_EN.contains(phrase), "English guidance: {phrase}");
            assert!(
                SKILL_BODY_JA.contains(phrase),
                "Japanese guidance: {phrase}"
            );
            assert!(
                render_skill_md().contains(phrase),
                "generated guidance: {phrase}"
            );
        }
    }

    /// Issue #3913 AC-2: the hook-delivered guidance tells every agent that
    /// raw `cargo test` / `cargo clippy` runs take the host-wide lease, in
    /// both languages and in the generated file.
    #[test]
    fn heavy_command_serialization_is_in_both_bodies_and_the_generated_file() {
        for phrase in [
            "## Heavy commands",
            "verify.lease.acquire",
            "verify.lease.release",
            "`cargo test`",
            "`cargo clippy`",
            "verify.run",
            "deferred",
            "issue.monitor.wait",
        ] {
            assert!(SKILL_BODY_EN.contains(phrase), "English guidance: {phrase}");
            assert!(
                SKILL_BODY_JA.contains(phrase),
                "Japanese guidance: {phrase}"
            );
            assert!(
                render_skill_md().contains(phrase),
                "generated guidance: {phrase}"
            );
        }
    }

    #[test]
    fn guidance_states_that_the_routine_stop_notice_is_not_an_escalation() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("ready for the next instruction"),
            "the guidance must name the notice agents mistook for an escalation"
        );
        assert!(
            rendered.contains("gwt withholds it entirely"),
            "the guidance must state that an open escalation suppresses the routine notice"
        );
    }

    #[test]
    fn guidance_routes_new_issue_registration_through_the_pm() {
        for body in [SKILL_BODY_EN, SKILL_BODY_JA] {
            assert!(
                body.contains("issue.create"),
                "the guidance must name the operation it is redirecting"
            );
        }
        assert!(
            SKILL_BODY_EN.contains("Do not call `issue.create`"),
            "English guidance must state the prohibition"
        );
        assert!(
            SKILL_BODY_JA.contains("`issue.create` を直接呼ばないでください"),
            "Japanese guidance must state the prohibition"
        );
        // AC-12: the prohibition covers registration only.
        assert!(
            SKILL_BODY_EN.contains("is never restricted"),
            "English guidance must keep issue.comment unrestricted"
        );
        assert!(
            SKILL_BODY_JA.contains("一切制限しません"),
            "Japanese guidance must keep issue.comment unrestricted"
        );
    }

    #[test]
    fn guidance_requires_an_explicit_resolution_to_close_an_escalation() {
        for body in [SKILL_BODY_EN, SKILL_BODY_JA] {
            assert!(
                body.contains("\"resolves\":[\"<blocked-entry-id>\"]"),
                "the guidance must show the exact resolution envelope"
            );
        }
    }

    #[test]
    fn render_skill_md_contains_required_canonical_phrases() {
        let rendered = render_skill_md();
        for phrase in required_phrases() {
            assert!(
                rendered.contains(phrase),
                "rendered SKILL.md is missing required canonical phrase: {phrase}\n\n--- rendered (first 4kB) ---\n{}",
                rendered.chars().take(4096).collect::<String>()
            );
        }
    }

    #[test]
    fn terminal_delivery_guidance_keeps_english_japanese_and_generated_outputs_in_sync() {
        for phrase in [
            "final Work update -> commit/push -> fresh verification -> PR mutation -> execution/build completion",
            "`chore(work):`",
            ".gwt/work/events/<digest-prefix>/*.jsonl",
            "git add -f -- .gwt/work/events/<digest-prefix>/<digest>.jsonl",
            "git ls-files --others --ignored --exclude-standard -- .gwt/work/events",
        ] {
            assert!(SKILL_BODY_EN.contains(phrase), "English guidance: {phrase}");
            assert!(SKILL_BODY_JA.contains(phrase), "Japanese guidance: {phrase}");
            assert!(
                render_skill_md().contains(phrase),
                "generated guidance: {phrase}"
            );
        }
    }

    #[test]
    fn guidance_commits_immutable_shards_and_freezes_the_legacy_monolith() {
        for body in [SKILL_BODY_EN, SKILL_BODY_JA] {
            for phrase in [
                ".gwt/work/events/<digest-prefix>/*.jsonl",
                ".gwt/work/events/<digest-prefix>/.*.jsonl.create-*",
                ".gwt/work/events/*.jsonl",
                ".gwt/work/events.jsonl",
                "git add -f -- .gwt/work/events/<digest-prefix>/<digest>.jsonl",
            ] {
                assert!(body.contains(phrase), "guidance is missing {phrase:?}");
            }
        }

        for phrase in [
            "immutable event shard",
            "frozen read-only compatibility history",
            "Never hand-edit, append to, delete, truncate, overwrite, or revert",
        ] {
            assert!(SKILL_BODY_EN.contains(phrase), "English guidance: {phrase}");
        }
        for phrase in [
            "immutable event shard",
            "read-only compatibility history",
            "手編集・追記・削除・切詰め・上書き・revert を禁止",
        ] {
            assert!(
                SKILL_BODY_JA.contains(phrase),
                "Japanese guidance: {phrase}"
            );
        }

        assert!(
            !SKILL_BODY_EN
                .contains("Include `.gwt/work/events.jsonl` in the related source commit"),
            "terminal delivery must not direct new writes to the frozen legacy monolith"
        );
        assert!(
            !SKILL_BODY_JA.contains("`.gwt/work/events.jsonl` は関連 source commit に含めます"),
            "Japanese terminal delivery must not direct new writes to the frozen legacy monolith"
        );
    }

    #[test]
    fn render_skill_md_uses_json_envelope_for_work_identity_examples() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("gwtd <<'JSON'"),
            "Work update examples must use the JSON envelope entrypoint"
        );
        assert!(
            rendered.contains("\"operation\":\"workspace.update\""),
            "Work update examples must name the JSON operation"
        );
        let legacy_board_title_mutation =
            ["board post", "--kind status", "--title-summary"].join(" ");
        assert!(
            !rendered.contains(&legacy_board_title_mutation),
            "Board post examples must not mutate Agent title/purpose"
        );
        assert!(
            !rendered.contains("--title-summary"),
            "generated coordination guidance must not expose the legacy title-summary flag"
        );
        let stale_commands = [
            ["gwtd", "board post"].join(" "),
            ["gwtd", "workspace update"].join(" "),
            ["gwtd", "search --"].join(" "),
            "--current-focus".to_string(),
        ];
        for stale in stale_commands {
            assert!(
                !rendered.contains(&stale),
                "generated coordination guidance must not expose legacy argv guidance: {stale}"
            );
        }
    }

    #[test]
    fn render_skill_md_uses_english_canonical_body() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("When you cross a reasoning milestone"),
            "generated SKILL.md must use English canonical prose"
        );
        assert!(
            !rendered.contains("推論の節目"),
            "generated SKILL.md must not render the Japanese localized body as canonical prose"
        );
    }

    #[test]
    fn render_skill_md_documents_broadcast_param_contract() {
        let rendered = render_skill_md();
        assert!(
            rendered.contains("params.broadcast:true"),
            "generated SKILL.md must document the explicit repo-wide broadcast parameter"
        );
        assert!(
            rendered.contains("Without `params.broadcast:true`"),
            "generated SKILL.md must explain that omitted broadcast keeps workspace/mention scoping"
        );
        assert!(
            !rendered.contains("mention 省略 → broadcast"),
            "generated SKILL.md must not claim that omitting mentions creates a broadcast post"
        );
    }

    // SPEC #3245 FR-004/FR-007: one guidance body for every session — the
    // Work-state instruction is always present and the curation framing is
    // gone (#3379 contradiction resolved by unification).
    #[test]
    fn guidance_is_a_single_body_with_work_state_instructions() {
        let body = render_skill_md();
        assert!(
            body.contains("\"operation\":\"workspace.update\""),
            "the single guidance keeps the workspace.update instruction"
        );
        assert!(
            !body.contains("intake sessions produce no Work"),
            "curation framing must be gone"
        );
    }

    #[test]
    fn render_skill_md_starts_with_yaml_frontmatter() {
        let rendered = render_skill_md();
        assert!(
            rendered.starts_with("---\n"),
            "SKILL.md must start with YAML frontmatter delimiter (---\\n)"
        );
        assert!(
            rendered.contains(&format!("name: {SKILL_NAME}\n")),
            "frontmatter must declare name: {SKILL_NAME}"
        );
        assert!(
            rendered.contains("description: Use proactively"),
            "frontmatter description must lead with the trigger keyword 'Use proactively'"
        );
        assert!(
            rendered.contains("regardless of project AGENTS.md / CLAUDE.md content"),
            "description must explicitly state project-AGENTS.md-independence"
        );
    }

    #[test]
    fn render_skill_md_wraps_body_in_managed_markers() {
        let rendered = render_skill_md();
        let begin_idx = rendered
            .find(MANAGED_BEGIN)
            .expect("managed begin marker missing");
        let end_idx = rendered
            .find(MANAGED_END)
            .expect("managed end marker missing");
        assert!(
            begin_idx < end_idx,
            "managed begin marker must precede managed end marker"
        );
    }

    #[test]
    fn generate_writes_skill_md_to_claude_and_codex_paths() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();

        let claude = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        let codex = tmp
            .path()
            .join(".codex/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");

        assert!(
            claude.exists(),
            "Claude SKILL.md not generated at {claude:?}"
        );
        assert!(codex.exists(), "Codex SKILL.md not generated at {codex:?}");

        let claude_content = std::fs::read_to_string(&claude).unwrap();
        let codex_content = std::fs::read_to_string(&codex).unwrap();
        assert_eq!(
            claude_content, codex_content,
            "Claude and Codex SKILL.md content must be byte-identical"
        );
        assert!(
            claude_content.contains("\"operation\":\"workspace.update\""),
            "written SKILL.md must contain canonical workspace.update JSON operation"
        );
    }

    #[test]
    fn generate_for_claude_only_does_not_touch_codex_path() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance_for_claude(tmp.path()).unwrap();

        assert!(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Claude SKILL.md must be created"
        );
        assert!(
            !tmp.path()
                .join(".codex/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Codex SKILL.md must NOT be created when only Claude is requested"
        );
    }

    #[test]
    fn generate_for_codex_only_does_not_touch_claude_path() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance_for_codex(tmp.path()).unwrap();

        assert!(
            tmp.path()
                .join(".codex/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Codex SKILL.md must be created"
        );
        assert!(
            !tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md")
                .exists(),
            "Claude SKILL.md must NOT be created when only Codex is requested"
        );
    }

    #[test]
    fn generate_is_idempotent() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();
        let first = std::fs::read_to_string(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md"),
        )
        .unwrap();

        generate_coordination_guidance(tmp.path()).unwrap();
        let second = std::fs::read_to_string(
            tmp.path()
                .join(".claude/skills")
                .join(SKILL_NAME)
                .join("SKILL.md"),
        )
        .unwrap();

        assert_eq!(
            first, second,
            "second invocation must produce byte-identical content (idempotent overwrite)"
        );
    }

    #[test]
    fn generate_overwrites_existing_stale_content() {
        let tmp = TempDir::new().unwrap();
        let path = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, "stale content from prior version\n").unwrap();

        generate_coordination_guidance(tmp.path()).unwrap();
        let after = std::fs::read_to_string(&path).unwrap();

        assert!(
            !after.contains("stale content from prior version"),
            "stale content must be replaced — this is a gwt-managed file"
        );
        assert!(
            after.contains("\"operation\":\"workspace.update\""),
            "fresh content must contain canonical workspace.update JSON operation"
        );
    }

    #[test]
    fn skill_body_en_contains_activity_bad_examples_and_rule() {
        let body = SKILL_BODY_EN;
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "checking CI",
            "reviewing PR",
            "purpose = work scope",
        ] {
            assert!(
                body.contains(phrase),
                "SKILL_BODY_EN must contain activity Bad example or rule phrase: {phrase}"
            );
        }
    }

    #[test]
    fn skill_body_ja_contains_activity_bad_examples_and_rule() {
        let body = SKILL_BODY_JA;
        for phrase in [
            "PR チェック中",
            "verifying tests",
            "fixing bug",
            "checking CI",
            "reviewing PR",
            "purpose は作業の scope",
        ] {
            assert!(
                body.contains(phrase),
                "SKILL_BODY_JA must contain activity Bad example or rule phrase: {phrase}"
            );
        }
    }

    #[test]
    fn rendered_skill_md_propagates_activity_rule_to_emitted_file() {
        let rendered = render_skill_md();
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "purpose = work scope",
        ] {
            assert!(
                rendered.contains(phrase),
                "render_skill_md() must propagate activity Bad example / rule: {phrase}"
            );
        }
    }

    #[test]
    fn generate_writes_byte_identical_skill_md_with_activity_rule_to_both_targets() {
        let tmp = TempDir::new().unwrap();
        generate_coordination_guidance(tmp.path()).unwrap();

        let claude = tmp
            .path()
            .join(".claude/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");
        let codex = tmp
            .path()
            .join(".codex/skills")
            .join(SKILL_NAME)
            .join("SKILL.md");

        let claude_content = std::fs::read_to_string(&claude).unwrap();
        let codex_content = std::fs::read_to_string(&codex).unwrap();

        assert_eq!(
            claude_content, codex_content,
            "Claude and Codex SKILL.md must remain byte-identical for Phase U-9 parity"
        );
        for phrase in [
            "PR check in progress",
            "verifying tests",
            "fixing bug",
            "purpose = work scope",
        ] {
            assert!(
                claude_content.contains(phrase),
                "materialized SKILL.md must carry the activity Bad example / rule: {phrase}"
            );
        }
    }

    #[test]
    fn skill_body_explicitly_overrides_project_agents_md() {
        // Compliance-gap regression guard: the SKILL.md body must
        // explicitly state that gwt's coordination rules supersede
        // project-local AGENTS.md / CLAUDE.md. Without this, agents
        // tend to deprioritize the skill in favor of empty project
        // context (see SPEC-1935 US-* design notes).
        let body = SKILL_BODY_EN;
        assert!(
            body.contains("AGENTS.md or CLAUDE.md"),
            "body must reference project AGENTS.md / CLAUDE.md to claim precedence"
        );
        assert!(
            body.contains("supersedes project-local documentation")
                || body.contains("regardless of"),
            "body must explicitly assert precedence over project docs"
        );
    }

    #[test]
    fn current_state_concept_uses_work_not_workspace() {
        // FR-357 (SPEC-2359 Phase W-12, Slice 1): the current-state concept
        // name must be "Work", not "Workspace". The public gwtd argv
        // subcommand has since been replaced by JSON envelopes, so generated
        // guidance must not reintroduce the legacy CLI form.
        let rendered = render_skill_md();
        assert!(
            rendered.contains("## Work (current state)"),
            "current-state section heading must use the Work concept name"
        );
        assert!(
            !rendered.contains("## Workspace (current state)"),
            "current-state section heading must not use the Workspace concept name"
        );
        assert!(
            rendered.contains("Work is current state"),
            "guidance must state 'Work is current state'"
        );
        assert!(
            !rendered.contains("Workspace is current state"),
            "guidance must not use the legacy 'Workspace is current state' phrasing"
        );
        assert!(
            !SKILL_DESCRIPTION.contains("Workspace update"),
            "skill description must not use the Workspace concept name"
        );
        assert!(
            SKILL_DESCRIPTION.contains("Work update"),
            "skill description must use Work for the current-state concept"
        );
        // Japanese translation aid must follow the same concept rename.
        assert!(
            SKILL_BODY_JA.contains("## Work (current state)"),
            "JA current-state heading must use the Work concept name"
        );
        assert!(
            SKILL_BODY_JA.contains("Work は current state"),
            "JA guidance must state 'Work は current state'"
        );
        assert!(
            !SKILL_BODY_JA.contains("Workspace は current state"),
            "JA guidance must not use the legacy 'Workspace は current state' phrasing"
        );
        let legacy_workspace_update = ["gwtd", "workspace", "update"].join(" ");
        assert!(
            !rendered.contains(&legacy_workspace_update),
            "generated guidance must not expose the legacy workspace update CLI example"
        );
    }
}
