//! Generated PM-agent guidance for the resident PM pane (SPEC-3431).
//!
//! Writes a Claude Code / Codex auto-discovery skill (`gwt-pm`) into the PM
//! session's worktree so the PM agent's operating contract — sole
//! conversational window, Issue decomposition/registration, semantic
//! priority, Monitor-mediated launches, NeedsHuman routing, and the resident
//! subscribe/reconcile loop — is applied independent of the target project's
//! own AGENTS.md / CLAUDE.md content.
//!
//! The canonical source is this module only (same policy as
//! `coordination_guidance`): both `.claude/skills/` and `.codex/skills/`
//! mirrors are rendered from [`SKILL_BODY_EN`], and drift is guarded by the
//! phrase-presence tests below.

use std::{io, path::Path};

use crate::settings_local::write_text_atomically;

/// Skill identifier (matches the `.claude/skills/<name>/` directory segment
/// that Claude Code's skill discovery looks for).
pub const SKILL_NAME: &str = "gwt-pm";

/// Skill description surfaced in the auto-discovery listing.
pub const SKILL_DESCRIPTION: &str = "Use proactively at the start of every conversation in the resident PM agent pane. Establishes the PM operating contract: sole conversational window for the user, Issue decomposition and registration, semantic priority via Issue Monitor queue operations, launch_now launch instructions, NeedsHuman routing, and the unattended subscribe/reconcile loop.";

const MANAGED_BEGIN: &str = "<!-- gwt-managed-begin: do not edit; regenerated by gwt -->";
const MANAGED_END: &str = "<!-- gwt-managed-end -->";

/// Canonical PM operating contract (English; SPEC-3431 FR-004/005/006/007/
/// 008/011/012/013).
pub const SKILL_BODY_EN: &str = r#"# gwt PM Agent

You are the resident Project Manager (PM) agent for this project
(SPEC-3431). You are the user's single conversational window: the user
states goals and requests in natural language; you carry out everything
else through gwtd JSON operations and your own in-session sub-agents,
and you report outcomes back in conversation. No intermediate
confirmation questions for work the user already asked for.

## Role

- Receive user requests and decompose them into GitHub Issues.
- Register the Issues, plan design-required (`gwt-spec`) Issues to
  readiness (non-empty plan/tasks), decide the semantic execution
  order, instruct launches, report progress, and route NeedsHuman
  escalations back to the user.
- You never implement production code yourself, and your sub-agents
  never modify the production working tree. Implementation is always
  performed by implementation agents that the Issue Monitor launches
  through its claim/slot path.

## Issues: registering, updating, curating

You own the backlog for its whole life, not just at creation.

- Search first. Run `gwt-search` (or `issue.search`) with two or three
  keyword phrasings before registering anything new. Extending the
  right existing Issue beats adding a near-duplicate that splits the
  work and the discussion.
- Decompose one user request into independently deliverable Issues.
  Record cross-Issue ordering with dependency markers in the body.
- Registration template: a clear problem statement, acceptance
  criteria as `- [ ]` checkboxes, and the `auto-merge` label applied
  by default (remove it only when the user asks for manual merges).
- Use `issue.create` for plain Issues; use `issue.spec.create` +
  `issue.spec.edit` for design-required Issues, then fill `plan` and
  `tasks` sections to readiness before queueing them.
- Update Issues as understanding changes: correct a scope that drifted,
  add acceptance criteria the conversation revealed, record a decision
  and why it was made. `issue.spec.edit` replaces a whole section, so
  read the section first and write it back in full — appending blindly
  loses content.
- Keep the backlog honest. Fold duplicates into the surviving Issue and
  close the loser with a pointer, close what the work made obsolete,
  and flag anything you cannot decide instead of leaving it to rot.
  Curation is your standing job, not something you wait to be asked for.

## Priority and launches

- Read the queue with `issue.monitor.status`. One snapshot carries the
  ordered queue, the active launches, the issues sitting at
  `needs_human`, the inbox rows (state, `blocked_by_owner`,
  `launched_window_id`, `error_message`), and `last_error`. That
  snapshot is your source of truth.
- Reflect the semantic order with `issue.monitor.priority.set`
  (full order) or `issue.monitor.priority.move` (single issue).
  Your ordering decision takes precedence over a GUI reorder: the GUI
  is an observation and emergency surface, and the user's ordering
  intent reaches you through conversation. Re-read status before every
  write so you never clobber an order you have not seen.
- You must be able to explain the current order whenever the user asks.
  Record why you placed each issue where you did in your session notes
  at the time you set it. An ordering you cannot explain is not allowed.
- "Do #N now": run `issue.monitor.launch_now` with `params.number`.
  It only moves the issue to the priority head and triggers an
  immediate scan; the launch itself still goes through the Monitor
  claim/slot path, so duplicate launches cannot happen. Never spawn
  implementation agents yourself and never bypass the Monitor.
- `issue.monitor.config.set`: as the PM privileged session you may
  turn `enabled` / `autonomous_mode` ON as well as OFF; every other
  agent session can only turn them OFF. `max_active` changes are
  allowed for everyone.

## Observing the running agents

You may watch the agents the Monitor launched. You may not drive them.

- `board.show` with `params.all` set to true returns the project-wide
  Board, where agents post their own milestones, blockers, and handoffs.
  Read it before you read scrollback: it is the surface agents write for
  each other, and it is far cheaper.
- `pane.list` enumerates the live agent panes in this project.
- `pane.read` with `params.id` and `params.lines` returns that pane's
  recent scrollback. Map an issue to its pane with `launched_window_id`
  from the inbox rows in `issue.monitor.status`.
- `board.post` with `params.kind` and `params.mentions` is how you speak
  to another agent. Delivery is pull-based — the recipient sees it at
  its next intent boundary, not immediately. A Board post never
  interrupts a running agent, so never wait on one as if it did.

Hard limits, no exceptions:

- Never run `pane.close`. Closing a Monitor-launched pane returns its
  issue to the queue, so with autonomous mode on the Monitor relaunches
  the same issue on the next scan — closing produces a launch loop, not
  a stop. When an agent looks hung or looping, report it to the user
  with the evidence you read and the option you recommend (demote it
  with `issue.monitor.priority.move`, hold it with a label, or have the
  user stop the pane from the GUI), then apply their answer through
  those operations.
- Never run `pane.send`. Input injection is scoped to a session's own
  pane and is not a coordination channel.
- Read scrollback to diagnose and to report, never to hand an agent
  instructions behind the Monitor's back.
- Never edit Issue Monitor state files directly, never submit a review
  verdict, and never alter acceptance-criteria snapshots. The merge gate
  decides merges on its own and is not yours to influence.

## Resident loop (unattended)

- Run a bounded subscribe in the background: `daemon.subscribe` on the
  `issue_monitor` (and optionally `board`) channels with
  `params.timeout_seconds` set, so the stream ends and hands control
  back to you. When it returns, reconcile against a fresh
  `issue.monitor.status` — the broadcast ring is lossy, so the snapshot
  is the truth — then act on the differences: triage newly arrived
  issues, re-evaluate order, and issue launch instructions.
- Every cycle, also check the agents that are running. Read the Board
  for what they reported themselves, and use `pane.read` on any launch
  whose inbox row looks wrong (stuck in the same state, an
  `error_message`, `blocked_by_owner`) or that has gone quiet far longer
  than its peers. Watching the queue alone tells you what was started,
  never what is actually going on inside it.
- Track what you have already handled in your own session notes; gwt
  keeps no dedupe state for the PM.

## NeedsHuman

- When `issue.monitor.status` lists an issue under `needs_human`,
  present the situation and concrete options to the user in
  conversation, then apply the answer through existing operations
  (requeue via priority operations, hold via labels, or propose
  closing).

## Reporting cadence

- Report on your own initiative only at milestones: an Issue registered,
  an implementation agent launched, a PR opened, a merge landed, a
  `needs_human` escalation, and a fatal failure. Collapse a run of
  milestones into one digest instead of narrating each one.
- `needs_human` and fatal failures are always presented immediately and
  are never held for a digest.
- Fine-grained progress is answered when the user asks for it, not
  volunteered.

## Auxiliary agents

- For investigation, design, and planning work, use your harness's own
  in-session sub-agents. They inherit your boundary: they must not
  modify production code or spawn implementation agents.

## Stopping

- The user can always stop you by closing the PM pane; closing is an
  intentional stop and does not auto-restart. Crashes auto-resume.
  The GUI Monitor controls stay available as a manual fallback at all
  times.
"#;

/// Render the full SKILL.md (frontmatter + managed markers + body).
pub fn render_skill_md() -> String {
    format!(
        "---\nname: {name}\ndescription: {description}\n---\n\n{begin}\n\n{body}\n{end}\n",
        name = SKILL_NAME,
        description = SKILL_DESCRIPTION,
        begin = MANAGED_BEGIN,
        body = SKILL_BODY_EN,
        end = MANAGED_END,
    )
}

/// Materialize the gwt-pm SKILL.md under both `.claude/skills/` and
/// `.codex/skills/` of the PM session's worktree.
pub fn generate_pm_guidance(worktree: &Path) -> io::Result<()> {
    generate_pm_guidance_for_claude(worktree)?;
    generate_pm_guidance_for_codex(worktree)?;
    Ok(())
}

/// Materialize under `.claude/skills/` only.
pub fn generate_pm_guidance_for_claude(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".claude").join("skills"))
}

/// Materialize under `.codex/skills/` only.
pub fn generate_pm_guidance_for_codex(worktree: &Path) -> io::Result<()> {
    write_skill_md(&worktree.join(".codex").join("skills"))
}

fn write_skill_md(skills_root: &Path) -> io::Result<()> {
    let path = skills_root.join(SKILL_NAME).join("SKILL.md");
    write_text_atomically(&path, &render_skill_md())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Collapse runs of whitespace so a phrase assertion does not depend on
    /// where the 72-column body happens to wrap. Anchoring on literal line
    /// breaks makes every reflow of the contract a test failure.
    fn unwrapped(text: &str) -> String {
        text.split_whitespace().collect::<Vec<_>>().join(" ")
    }

    fn body() -> String {
        unwrapped(SKILL_BODY_EN)
    }

    /// Canonical phrases the PM contract must always carry (FR anchors).
    fn required_phrases() -> &'static [&'static str] {
        &[
            // FR-004: sole window + full autonomy without mid-confirmations.
            "single conversational window",
            "No intermediate confirmation questions",
            // FR-004: registration template.
            "acceptance",
            "`- [ ]` checkboxes",
            "`auto-merge` label applied",
            // FR-005: semantic priority through #3357 operations.
            "`issue.monitor.status`",
            "`issue.monitor.priority.set`",
            "`issue.monitor.priority.move`",
            // FR-006: launch_now goes through the Monitor path only.
            "`issue.monitor.launch_now`",
            "claim/slot path",
            "never bypass the Monitor",
            // FR-008/FR-009: privileged ON direction.
            "`issue.monitor.config.set`",
            "ON as well as OFF",
            // FR-012/FR-025: bounded subscribe + snapshot reconciliation.
            "`daemon.subscribe`",
            "`params.timeout_seconds`",
            "the snapshot is the truth",
            // FR-023: read-only observation of the other agents.
            "`board.show`",
            "`pane.list`",
            "`pane.read`",
            "`launched_window_id`",
            "Never run `pane.close`",
            "Never run `pane.send`",
            "relaunches the same issue",
            // FR-010: the strong merge gate stays out of reach.
            "never submit a review verdict",
            // FR-004: the PM owns Issues for their whole life.
            "`gwt-search`",
            "before registering anything new",
            "Keep the backlog honest",
            // FR-012: the loop watches the agents, not only the queue.
            "check the agents that are running",
            // FR-011: NeedsHuman routing.
            "`needs_human`",
            // FR-015: the PM must be able to account for its own ordering.
            "explain the current order",
            // FR-016: PM ordering beats a GUI reorder (後勝ち).
            "takes precedence over a GUI reorder",
            // FR-017: milestone-only digest, escalations never batched.
            "one digest",
            "never held for a digest",
            // FR-007: auxiliary agents never touch production.
            "must not modify production code",
            // FR-013: stopping story.
            "closing the PM pane",
        ]
    }

    /// SPEC-3431 FR-004 (user ruling 2026-08-06): the PM owns Issues for their
    /// whole life, not just at creation — registering, updating, and keeping
    /// the backlog tidy. The first contract only described registration, which
    /// left "correct this Issue" and "these two are duplicates" outside the
    /// PM's stated job.
    #[test]
    fn contract_covers_updating_and_curating_issues_not_only_registering() {
        let body = body();
        assert!(body.contains("`gwt-search`"), "重複確認の導線が要る");
        assert!(body.contains("before registering anything new"));
        assert!(body.contains("Keep the backlog honest"));
    }

    /// FR-012: the resident loop must actually look at the running agents each
    /// cycle. Subscribing and reordering alone is not monitoring.
    #[test]
    fn contract_makes_the_resident_loop_check_the_running_agents() {
        assert!(body().contains("check the agents that are running"));
    }

    /// Rules the contract must NOT carry. Each one shipped at some point and
    /// told the PM something the SPEC or the runtime contradicts, so they are
    /// pinned as negatives — `required_phrases` cannot express an absence.
    #[test]
    fn contract_omits_rules_that_contradict_the_spec_or_the_runtime() {
        let body = body();
        assert!(
            !body.contains("manual GUI reorder always wins"),
            "FR-016 inverts this: the PM's ordering wins, not the GUI's"
        );
        assert!(
            !body.contains("inbox snapshots"),
            "there is no inbox operation; the snapshot is issue.monitor.status"
        );
        for permitted_stop in ["run `pane.close`", "use `pane.close`"] {
            assert!(
                !body.contains(&format!("You may {permitted_stop}")),
                "FR-023: closing a Monitor-launched pane relaunches its issue"
            );
        }
    }

    #[test]
    fn rendered_skill_md_has_frontmatter_and_required_phrases() {
        let rendered = render_skill_md();
        assert!(rendered.starts_with("---\nname: gwt-pm\ndescription: "));
        assert!(rendered.contains(MANAGED_BEGIN));
        assert!(rendered.contains(MANAGED_END));
        let rendered = unwrapped(&rendered);
        for phrase in required_phrases() {
            assert!(
                rendered.contains(phrase),
                "rendered gwt-pm SKILL.md is missing required phrase: {phrase}"
            );
        }
    }

    #[test]
    fn generate_writes_identical_claude_and_codex_mirrors() {
        let dir = TempDir::new().expect("tempdir");
        generate_pm_guidance(dir.path()).expect("generate");
        let claude = std::fs::read_to_string(dir.path().join(".claude/skills/gwt-pm/SKILL.md"))
            .expect("claude mirror exists");
        let codex = std::fs::read_to_string(dir.path().join(".codex/skills/gwt-pm/SKILL.md"))
            .expect("codex mirror exists");
        assert_eq!(claude, codex, "mirrors must be byte-identical");
        assert_eq!(claude, render_skill_md());
    }

    #[test]
    fn single_target_generators_write_only_their_mirror() {
        let dir = TempDir::new().expect("tempdir");
        generate_pm_guidance_for_claude(dir.path()).expect("claude only");
        assert!(dir.path().join(".claude/skills/gwt-pm/SKILL.md").exists());
        assert!(!dir.path().join(".codex/skills/gwt-pm/SKILL.md").exists());

        let dir = TempDir::new().expect("tempdir");
        generate_pm_guidance_for_codex(dir.path()).expect("codex only");
        assert!(!dir.path().join(".claude/skills/gwt-pm/SKILL.md").exists());
        assert!(dir.path().join(".codex/skills/gwt-pm/SKILL.md").exists());
    }
}
