using System.Threading;
using Cysharp.Threading.Tasks;
using Gwt.Core.Models;

namespace Gwt.Agent.Lead
{
    public class LeadMergeManager : ILeadMergeManager
    {
        readonly IGitHubService _github;
        readonly IGitService _git;

        public LeadMergeManager(IGitHubService github, IGitService git)
        {
            _github = github;
            _git = git;
        }

        public async UniTask<PullRequest> CreateTaskPrAsync(LeadPlannedTask task, string baseBranch, string repoRoot, CancellationToken ct = default)
        {
            var title = $"[Lead] {task.Title}";
            var body = $"## Auto-generated by Lead\n\n" +
                       $"**Task ID**: {task.TaskId}\n" +
                       $"**Description**: {task.Description}\n\n" +
                       $"**Branch**: {task.Branch}\n" +
                       $"**Agent**: {task.AgentType}";

            var pr = await _github.CreatePullRequestAsync(repoRoot, title, body, task.Branch, baseBranch, ct);
            task.PrNumber = pr.Number;
            return pr;
        }

        public async UniTask<bool> TryMergeAsync(long prNumber, string repoRoot, CancellationToken ct = default)
        {
            var status = await _github.GetPrStatusAsync(repoRoot, prNumber, ct);
            return status.Mergeable == "MERGEABLE";
        }

        public async UniTask CleanupWorktreeAsync(LeadPlannedTask task, string repoRoot, CancellationToken ct = default)
        {
            if (!string.IsNullOrEmpty(task.WorktreePath))
            {
                await _git.DeleteWorktreeAsync(repoRoot, task.WorktreePath, false, ct);
                task.WorktreePath = null;
            }
        }
    }
}
