#!/usr/bin/env bash
set -euo pipefail

bash scripts/run-node-tests-with-linkedom.sh \
  crates/gwt/web/__tests__/contrast.test.mjs \
  crates/gwt/web/__tests__/theme-manager.test.mjs \
  crates/gwt/web/__tests__/theme-segmented.test.mjs \
  crates/gwt/web/__tests__/hotkey.test.mjs \
  crates/gwt/web/__tests__/index-settings-panel.test.mjs \
  crates/gwt/web/__tests__/index-status-controller.test.mjs \
  crates/gwt/web/__tests__/index-works-scope.test.mjs \
  crates/gwt/web/__tests__/launch-wizard-intake.test.mjs \
  crates/gwt/web/__tests__/operator-chrome-structure.test.mjs \
  crates/gwt/web/__tests__/operator-shell-runtime.test.mjs \
  crates/gwt/web/__tests__/provider-usage-surface.test.mjs \
  crates/gwt/web/__tests__/operator-rail.test.mjs \
  crates/gwt/web/__tests__/board-surface.test.mjs \
  crates/gwt/web/__tests__/improvement-inbox-surface.test.mjs \
  crates/gwt/web/__tests__/board-lane.test.mjs \
  crates/gwt/web/__tests__/focus-trap.test.mjs \
  crates/gwt/web/__tests__/kanban-structure.test.mjs \
  crates/gwt/web/__tests__/quiet-work-ui-contract.test.mjs \
  crates/gwt/web/__tests__/kanban-dnd.test.mjs \
  crates/gwt/web/__tests__/kanban-drawer.test.mjs \
  crates/gwt/web/__tests__/knowledge-kanban-load-recovery.test.mjs \
  crates/gwt/web/__tests__/agent-kanban-surface.test.mjs \
  crates/gwt/web/__tests__/workspace-kanban-surface.test.mjs \
  crates/gwt/web/__tests__/launch-pending-controller.test.mjs \
  crates/gwt/web/__tests__/workspace-resume-picker-pending.test.mjs \
  crates/gwt/web/__tests__/issue-monitor-surface.test.mjs \
  crates/gwt/web/__tests__/connection-overlay.test.mjs \
  crates/gwt/web/__tests__/update-button.test.mjs \
  crates/gwt/web/__tests__/window-docking.test.mjs \
  crates/gwt/web/__tests__/terminal-context-menu.test.mjs \
  crates/gwt/web/__tests__/terminal-copy-shortcut.test.mjs \
  crates/gwt/web/__tests__/terminal-wheel-scroll.test.mjs \
  crates/gwt/web/__tests__/terminal-output-buffer.test.mjs \
  crates/gwt/web/__tests__/canvas-wheel-gesture.test.mjs \
  crates/gwt/web/__tests__/terminal-viewport-reflow.test.mjs \
  crates/gwt/web/__tests__/window-geometry-sync.test.mjs \
  crates/gwt/web/__tests__/window-lane-identity.test.mjs \
  crates/gwt/web/__tests__/fleet-minimap.test.mjs \
  crates/gwt/web/__tests__/custom-agent-env-editor.test.mjs \
  crates/gwt/web/__tests__/settings-system-tab.test.mjs \
  crates/gwt/web/__tests__/settings-agent-backends-tab.test.mjs \
  crates/gwt/web/__tests__/launch-wizard-backend-picker.test.mjs \
  crates/gwt/web/__tests__/socket-receive-dispatcher.test.mjs \
  crates/gwt/web/__tests__/ui-trace-profiler.test.mjs \
  crates/gwt/web/__tests__/ui-trace-wiring.test.mjs \
  crates/gwt/web/__tests__/interaction-guard.test.mjs \
  crates/gwt/web/__tests__/wizard-interaction-guard-wiring.test.mjs \
  crates/gwt/web/__tests__/viewport-persist-throttle.test.mjs \
  crates/gwt/web/__tests__/viewport-sync.test.mjs \
  crates/gwt/web/__tests__/agent-completion-notifications.test.mjs \
  crates/gwt/web/__tests__/autonomous-notifications.test.mjs \
  crates/gwt/web/__tests__/toast-host.test.mjs \
  crates/gwt/web/__tests__/project-switcher.test.mjs \
  crates/gwt/web/__tests__/project-tabs-renderer.test.mjs \
  crates/gwt/web/__tests__/close-project-tab.smoke.test.mjs \
  crates/gwt/web/__tests__/window-tabs-renderer.test.mjs \
  crates/gwt/web/__tests__/project-tab-style.test.mjs \
  crates/gwt/web/__tests__/playwright-embedded-routes.test.mjs \
  crates/gwt/web/__tests__/viewport-persist-wiring.test.mjs \
  crates/gwt/web/__tests__/system-settings-interaction-guard-wiring.test.mjs \
  crates/gwt/web/__tests__/clone-modal-focus-guard.test.mjs \
  crates/gwt/web/__tests__/clone-modal-focus-guard-wiring.test.mjs \
  crates/gwt/web/__tests__/recent-row-style.test.mjs \
  crates/gwt/web/__tests__/release-notes-window.test.mjs \
  crates/gwt/web/__tests__/console-window.test.mjs \
  crates/gwt/web/__tests__/surface-window-reopen.test.mjs \
  crates/gwt/web/__tests__/preset-modal-surface-deck.test.mjs \
  crates/gwt/web/__tests__/logs-process-facet.test.mjs \
  crates/gwt/web/__tests__/window-runtime-state.test.mjs \
  crates/gwt/web/__tests__/window-list-model.test.mjs \
  crates/gwt/web/__tests__/window-close-confirm-modal.test.mjs
